(function(){
'use strict';
function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim().toUpperCase()}
function parseBr(v){if(!v)return null;try{if(typeof parseBR==='function')return parseBR(v)}catch(e){}var m=String(v).match(/^(\d{2})\/(\d{2})\/(\d{4})$/);if(!m)return null;var d=new Date(+m[3],+m[2]-1,+m[1]);return isNaN(d.getTime())?null:d}
function br(d){if(!d||isNaN(d.getTime()))return'';return String(d.getDate()).padStart(2,'0')+'/'+String(d.getMonth()+1).padStart(2,'0')+'/'+d.getFullYear()}
function parent(c){if(!c)return null;if(c.tipo==='Contrato')return c;if(c.contratoPai)return contracts.find(function(x){return x.tipo==='Contrato'&&String(x.id)===String(c.contratoPai)})||null;return null}
function filhos(p){return contracts.filter(function(x){return x.tipo==='Termo Aditivo'&&String(x.contratoPai)===String(p.id)})}
function meta(a){try{if(typeof tdngoMetaAditivo==='function')return tdngoMetaAditivo(a)||null}catch(e){}var s=String(a&&a.prorrogacao||'');var i=s.indexOf('TDNGO_ADITIVO:');if(i>=0){try{return JSON.parse(s.slice(i+'TDNGO_ADITIVO:'.length))}catch(e){}}return null}
function familyEnd(p){var end=parseBr(p.vigenciaFim),src=p;filhos(p).forEach(function(a){var m=meta(a);if(m&&m.vigencia===false)return;var d=parseBr(a.vigenciaFim);if(d&&(!end||d>end)){end=d;src=a}});return{fim:end,fonte:src}}
function familyStatus(p){var s=norm(p.statusContrato),ve=familyEnd(p),today=new Date();today.setHours(0,0,0,0);if(s.indexOf('SUSPEN')>=0)return{cls:'suspenso',txt:'Suspenso'};if(s.indexOf('NEGOCI')>=0)return{cls:'negociacao',txt:'Em negociação'};if(!ve.fim)return{cls:'negociacao',txt:'Sem vigência'};var diff=Math.ceil((ve.fim-today)/86400000),hasAd=ve.fonte&&ve.fonte.id!==p.id;if(diff<0){if(s.indexOf('ENCERR')>=0)return{cls:'encerrado',txt:'Encerrado'};return{cls:'vencido',txt:'Contrato vencido'}}if(diff<=60)return{cls:'vencendo',txt:hasAd?'Vencendo (com aditivo)':'Vencendo'};return hasAd?{cls:'aditivo-vig',txt:'Vigente com aditivo'}:{cls:'vigente',txt:'Contrato vigente'}}
var originalGetStatus=typeof getStatusLabel==='function'?getStatusLabel:null;
if(originalGetStatus){getStatusLabel=function(c){if(!c)return originalGetStatus(c);if(c.tipo==='Contrato')return familyStatus(c);if(typeof isAditivoSubstituido==='function'&&isAditivoSubstituido(c))return{cls:'substituido',txt:'Aditivo substituído'};var d=parseBr(c.vigenciaFim),today=new Date();today.setHours(0,0,0,0);if(!d)return originalGetStatus(c);var diff=Math.ceil((d-today)/86400000);if(diff<0)return{cls:'vencido',txt:'Aditivo vencido'};if(diff<=60)return{cls:'vencendo',txt:'Aditivo vigente'};return{cls:'aditivo-vig',txt:'Aditivo vigente'}}}
if(typeof getVigStatus==='function'){getVigStatus=function(c){if(c&&c.tipo==='Contrato'){var d=familyEnd(c).fim;if(!d)return'ativo';var now=new Date();now.setHours(0,0,0,0);var diff=Math.ceil((d-now)/86400000);return diff<0?'vencido':diff<=60?'vencendo':'ativo'}var d2=parseBr(c&&c.vigenciaFim);if(!d2)return'ativo';var n=new Date();n.setHours(0,0,0,0);var df=Math.ceil((d2-n)/86400000);return df<0?'vencido':df<=60?'vencendo':'ativo'}}
function alertContracts(){return contracts.filter(function(c){if(!c||c.tipo!=='Contrato')return false;var st=familyStatus(c);return st.cls==='vencendo'||st.cls==='vencido'||st.cls==='encerrado'})}
window.renderAlertas=function(){var body=document.getElementById('alertas-body');if(!body)return;var all=alertContracts(),vencendo=all.filter(function(c){return familyStatus(c).cls==='vencendo'}),vencidos=all.filter(function(c){var x=familyStatus(c).cls;return x==='vencido'||x==='encerrado'}),badge=document.getElementById('nav-alert-badge');if(badge){badge.textContent=all.length;badge.style.display=all.length?'inline':'none'}if(!all.length){body.innerHTML='<div class="empty-state"><span class="empty-icon">✅</span>Nenhum contrato original exige atenção no momento</div>';return}function card(c,kind){var ve=familyEnd(c),st=familyStatus(c),src=ve.fonte&&ve.fonte.id!==c.id?' · Vigência definida pelo '+(ve.fonte.numero||'aditivo'):'';return '<div class="alert-card '+kind+'" onclick="showDetail(\''+c.id+'\')"><div class="alert-title">Contrato '+(c.numero||'—')+' — '+(c.empresa||'—')+'</div><div class="alert-sub">'+(c.objeto||'')+' · Vencimento efetivo: <strong>'+br(ve.fim)+'</strong>'+src+(c.fiscalNome?' · Fiscal: '+c.fiscalNome:'')+'</div></div>'}var h='';if(vencendo.length){h+='<h3 style="font-size:14px;font-weight:700;margin-bottom:10px;color:var(--yellow)">⚠ Contratos que vencem nos próximos 60 dias ('+vencendo.length+')</h3>'+vencendo.map(function(c){return card(c,'yellow')}).join('')}if(vencidos.length){h+='<h3 style="font-size:14px;font-weight:700;margin:18px 0 10px;color:var(--red)">⛔ Contratos vencidos/encerrados ('+vencidos.length+')</h3>'+vencidos.map(function(c){return card(c,'red')}).join('')}body.innerHTML=h}
function fixUnitList(){try{if(!Array.isArray(unitList))return;unitList=unitList.filter(function(u){return norm(u.nome)!=='UPA SUL'});var ub=unitList.find(function(u){return norm(u.nome)==='UBDS VILA VIRGINIA'});if(!ub)console.warn('[Contratos] UBDS Vila Virgínia não encontrada no cadastro central.')}catch(e){console.warn(e)}}
var oldLoadUnits=typeof loadUnits==='function'?loadUnits:null;
if(oldLoadUnits){loadUnits=async function(){var r=await contratosApi('units',{});if(!r||!r.ok||!Array.isArray(r.data)){unitList=[];showNotif('Não foi possível carregar as unidades oficiais do TDNGo. O cadastro de contratos foi bloqueado até a lista ser carregada.','err');return}unitList=r.data.map(function(u){return{id:String(u.ID||u.id),nome:u.Nome||u.nome,tipo:u.Tipo||u.tipo||'',lat:u.Lat,lng:u.Lng,cep:u.CEP||'',logradouro:u.Logradouro||'',numero:u.Numero||'',bairro:u.Bairro||'',cidade:u.Cidade||'',uf:u.UF||'',telefone:u.Telefone||'',responsavel:u.Responsavel||'',ativo:u.Ativo!==false}});fixUnitList();try{refreshUnitSelects()}catch(e){}}}
var oldRefresh=typeof refreshAll==='function'?refreshAll:null;if(oldRefresh){refreshAll=function(){var r=oldRefresh();try{renderAlertas()}catch(e){}return r}}
fixUnitList();try{renderAlertas()}catch(e){}
})();
