(()=>{
'use strict';
const $=s=>document.querySelector(s);
const PUBLIC_CATALOG='https://nsbhhmrhzkqkaoznaeif.supabase.co/functions/v1/tdngo-manutencao-public-catalog';
function txt(v){return String(v||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function valFromCards(root,label){if(!root)return null;for(const c of root.children){const l=c.querySelector('span');const b=c.querySelector('b');if(!l||!b)continue;if(txt(l.textContent).includes(txt(label)))return b.textContent.trim()}return null}
function metricCard(value,label){return `<div class="card ops-card"><b>${value??'0'}</b><span>${label}</span></div>`}
function consolidateDesktopKpis(){if(matchMedia('(max-width:760px)').matches)return;const ops=$('#ops-desktop .ops-grid');if(!ops||ops.dataset.v4==='1')return;const legacy=$('#dash-kpis');const open=valFromCards(ops,'operação aberta')||valFromCards(legacy,'chamados em aberto')||'0';const unassigned=valFromCards(ops,'sem responsável')||'0';const attending=valFromCards(legacy,'em atendimento')||'0';const critical=valFromCards(ops,'p1 / p2')||'0';const late=valFromCards(ops,'sla vencido')||valFromCards(legacy,'sla de resolução vencido')||'0';const closed=valFromCards(legacy,'concluídos hoje')||'0';const oncall=valFromCards(legacy,'abertos em sobreaviso')||'0';ops.dataset.v4='1';ops.innerHTML=metricCard(open,'Abertos')+metricCard(unassigned,'Sem responsável')+metricCard(attending,'Em atendimento')+metricCard(critical,'P1 / P2')+metricCard(late,'SLA vencido')+metricCard(closed,'Concluídos hoje')+metricCard(oncall,'Sobreaviso')}
function emptyTeamHtml(){return `<div class="v4-team-empty"><b>Nenhum profissional de manutenção configurado.</b><p>Cadastre técnicos, auxiliares e responsáveis para acompanhar disponibilidade, atendimentos e sobreaviso em tempo real.</p><button class="btn sm" type="button" onclick="showPage('settings')">Configurar equipe</button></div>`}
function fixTeamEmpty(){document.querySelectorAll('.ops-panel').forEach(panel=>{const h=panel.querySelector('h3');if(txt(h?.textContent)!=='equipe agora')return;const team=panel.querySelector('.team-list');if(!team||team.dataset.v4Empty==='1')return;const t=txt(team.textContent);if(t.includes('equipe nao disponivel para este perfil')||(!team.querySelector('.team-row')&&!team.querySelector('.v4-team-empty')&&team.children.length<=1)){team.dataset.v4Empty='1';team.innerHTML=emptyTeamHtml()}})}
function addInstallToSettings(){if(matchMedia('(max-width:760px)').matches)return;const page=$('#page-settings'),grid=page?.querySelector('.settings-grid');if(!page||!grid)return;const existing=[...page.querySelectorAll('.v4-install-card')];if(existing.length){existing.slice(1).forEach(x=>x.remove());return}const card=document.createElement('div');card.className='card settings-card v4-install-card';card.innerHTML=`<div class="section-title"><h3>Aplicativo da manutenção</h3></div><p class="small muted" style="line-height:1.5;margin:0 0 10px">Instale o módulo como aplicativo para acesso rápido no celular ou computador. No celular, a experiência é otimizada para operação em campo.</p><button class="btn" type="button" onclick="installMaintenanceApp()">Instalar no dispositivo</button>`;grid.appendChild(card)}
function cleanDesktop(){if(matchMedia('(max-width:760px)').matches)return;document.querySelectorAll('#side-nav .mn-open-side').forEach(e=>e.style.display='none');document.querySelectorAll('.side-foot .install-btn').forEach(e=>e.style.display='none');const sub=$('#page-dashboard .page-head p');if(sub)sub.textContent='Fila, equipe, prioridades e SLA em tempo real.';consolidateDesktopKpis();fixTeamEmpty();addInstallToSettings()}
function cleanMobile(){if(!matchMedia('(max-width:760px)').matches)return;const title=$('#mobile-title');if(title&&title.textContent!=='Manutenção')title.textContent='Manutenção';const field=$('#page-field');if(field){const head=field.querySelector('.page-head');if(head){const action=head.querySelector('.actions');if(action&&!action.classList.contains('v4-mobile-page-actions'))action.classList.add('v4-mobile-page-actions')}const root=$('#field-root');if(root){const notes=[...root.querySelectorAll('.v4-live-note')];if(notes.length>1)notes.slice(1).forEach(n=>n.remove());if(!notes.length&&head){const note=document.createElement('div');note.className='v4-live-note';note.innerHTML='<span class="live-dot"></span><span>Atualização automática ativa</span>';head.insertAdjacentElement('afterend',note)}}}fixTeamEmpty()}
function fillPublicSelect(select,rows){if(!select)return;const current=select.value;select.innerHTML='<option value="">Selecione...</option>'+rows.map(x=>`<option value="${String(x.id).replace(/"/g,'&quot;')}">${String(x.nome||'').replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}</option>`).join('');if([...select.options].some(o=>o.value===current))select.value=current}
async function repairPublicCatalog(){const unit=$('#p-unit'),cat=$('#p-category');if(!unit||!cat)return;if(unit.options.length>1&&cat.options.length>1)return;try{const r=await fetch(PUBLIC_CATALOG,{method:'GET',cache:'no-store',credentials:'omit'});const d=await r.json();if(!r.ok||d?.ok===false)throw new Error(d?.message||`HTTP ${r.status}`);if(!Array.isArray(d.units)||!Array.isArray(d.categories))throw new Error('Catálogo inválido.');fillPublicSelect(unit,d.units);fillPublicSelect(cat,d.categories);const toast=$('#toast');if(toast&&txt(toast.textContent).includes('nao foi possivel carregar unidades e categorias')){toast.style.display='none';toast.textContent=''}console.info('[Manutenção] catálogo público carregado por rota dedicada:',d.units.length,'unidades /',d.categories.length,'categorias')}catch(e){console.error('[Manutenção] falha no catálogo público dedicado',e)}}
function clean(){cleanDesktop();cleanMobile()}
let queued=false;function schedule(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;clean()})}
function init(){clean();repairPublicCatalog();const root=$('#internal-app');if(root)new MutationObserver(schedule).observe(root,{childList:true,subtree:true});window.addEventListener('resize',schedule);setTimeout(clean,250);setTimeout(clean,700);setTimeout(clean,1500);setTimeout(repairPublicCatalog,350);setTimeout(repairPublicCatalog,1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
