(()=>{
'use strict';
if(window.__TDNGO_MANUT_V6__)return;window.__TDNGO_MANUT_V6__=true;
const EXT='https://nsbhhmrhzkqkaoznaeif.supabase.co/functions/v1/tdngo-manutencao-ext-api';
const MAIN='https://nsbhhmrhzkqkaoznaeif.supabase.co/functions/v1/tdngo-manutencao-api';
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let lastTicketId=null,lastTicket=null,wrappedOpen=false,wrappedTrack=false;
function sess(){try{const r=sessionStorage.getItem('fhsl_session')||localStorage.getItem('fhsl_session');return r?JSON.parse(r):null}catch{return null}}
function tok(){return sess()?.tdngoToken||''}
function toast(m,t=''){const e=$('toast');if(!e)return;e.textContent=String(m||'').toLocaleUpperCase('pt-BR');e.className='toast '+t;e.style.display='block';clearTimeout(e._v6);e._v6=setTimeout(()=>e.style.display='none',4200)}
async function api(url,action,p={},auth=true){const h={'Content-Type':'application/json'};if(auth){const t=tok();if(!t)throw new Error('SESSÃO EXPIRADA.');h.Authorization='Bearer '+t}const r=await fetch(url,{method:'POST',headers:h,body:JSON.stringify({...p,action}),cache:'no-store'});const tx=await r.text();let d;try{d=JSON.parse(tx)}catch{d={ok:false,message:tx||`HTTP ${r.status}`}}if(!r.ok||d.ok===false)throw new Error(d.message||`HTTP ${r.status}`);return d}
function money(v){return v==null?'—':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}
function maskCpfIn(root=document){const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT,{acceptNode:n=>{const p=n.parentElement;if(!p||p.closest('.v6-sensitive'))return NodeFilter.FILTER_REJECT;return /\b\d{3}\.\d{3}\.\d{3}-\d{2}\b/.test(n.nodeValue||'')?NodeFilter.FILTER_ACCEPT:NodeFilter.FILTER_REJECT}}),a=[];while(w.nextNode())a.push(w.currentNode);for(const n of a)n.nodeValue=n.nodeValue.replace(/\b\d{3}\.\d{3}\.\d{3}-(\d{2})\b/g,'***.***.***-$1')}
function urlB64(s){const p='='.repeat((4-s.length%4)%4),b=(s+p).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(b),a=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)a[i]=raw.charCodeAt(i);return a}
async function enablePush(){
 if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window)){toast('WEB PUSH NÃO É SUPORTADO NESTE NAVEGADOR.','err');return}
 const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent),standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone===true;
 if(isiOS&&!standalone){toast('NO IPHONE, INSTALE O TDNGO MANUTENÇÃO NA TELA DE INÍCIO PARA RECEBER PUSH.','err');window.installMaintenanceApp?.();return}
 const perm=await Notification.requestPermission();if(perm!=='granted'){toast('NOTIFICAÇÕES NÃO AUTORIZADAS.','err');return}
 const reg=await navigator.serviceWorker.ready,key=await api(EXT,'push_public_key'),existing=await reg.pushManager.getSubscription();
 let sub=existing;if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:urlB64(key.publicKey)});
 await api(EXT,'push_subscribe',{subscription:sub.toJSON(),plataforma:isiOS?'IOS':/android/i.test(navigator.userAgent)?'ANDROID':'DESKTOP'});
 localStorage.setItem('tdngo_manut_push_enabled','1');decoratePush();toast('WEB PUSH 24H ATIVADO NESTE DISPOSITIVO.','ok')
}
async function ensurePush(){if(localStorage.getItem('tdngo_manut_push_enabled')!=='1'||Notification.permission!=='granted')return;try{const reg=await navigator.serviceWorker.ready,sub=await reg.pushManager.getSubscription();if(!sub)return enablePush();await api(EXT,'push_subscribe',{subscription:sub.toJSON(),plataforma:/iphone|ipad|ipod/i.test(navigator.userAgent)?'IOS':/android/i.test(navigator.userAgent)?'ANDROID':'DESKTOP'})}catch{}}
function decoratePush(){const active=localStorage.getItem('tdngo_manut_push_enabled')==='1'&&Notification.permission==='granted';document.querySelectorAll('button').forEach(b=>{const t=(b.textContent||'').toLowerCase();if(t.includes('ativar alertas')||t.includes('alertas ativos')||t.includes('web push')){b.textContent=active?'Alertas 24h ativos':'Ativar alertas 24h';if(active)b.classList.add('v5-alert-button-active')}});const bar=document.querySelector('#page-dashboard .live-banner');if(active&&bar&&!bar.querySelector('.v6-push-ok'))bar.insertAdjacentHTML('beforeend','<span class="v6-push-ok">● WEB PUSH ATIVO</span>')}
async function detailMain(id){return api(MAIN,'detail',{id})}
async function extras(id){return api(EXT,'extras',{id})}
function materialHtml(m){return `<div class="v6-material-row"><div><b>${esc(m.descricao)}</b>${m.fornecedor?`<small>${esc(m.fornecedor)}</small>`:''}</div><div>${esc(m.quantidade)} ${esc(m.unidade_medida)}</div><div>${esc(m.origem)}</div><div>${money(m.custo_total)}</div><button class="btn sm red" onclick="v6DeleteMaterial('${m.id}')">Remover</button></div>`}
async function injectExtras(id){lastTicketId=id;try{const d=await extras(id),body=$('detail-body');if(!body)return;body.querySelectorAll('.v6-section').forEach(x=>x.remove());const asset=d.asset;const mats=d.materials||[],total=mats.reduce((s,x)=>s+Number(x.custo_total||0),0);const h=document.createElement('div');h.innerHTML=`<section class="v6-section"><div class="v6-section-head"><h3>Patrimônio / equipamento</h3><span class="spacer"></span><button class="btn sm" onclick="v6OpenAssetSearch('${id}')">${asset?'Alterar vínculo':'Vincular patrimônio'}</button></div>${asset?`<div class="v6-asset"><div><b>${esc(asset.codigo_patrimonio)} · ${esc(asset.descricao)}</b><small>${esc([asset.fabricante,asset.modelo,asset.numero_serie].filter(Boolean).join(' · ')||'SEM DADOS COMPLEMENTARES')}</small><small>STATUS TÉCNICO: ${esc(asset.status_tecnico||'—')}${asset.criticidade_assistencial?` · CRITICIDADE ${esc(asset.criticidade_assistencial)}`:''}</small></div><button class="btn sm" onclick="v6UnlinkAsset('${id}')">Desvincular</button></div>`:'<div class="muted small">Nenhum patrimônio vinculado. Vincule quando o chamado estiver relacionado a equipamento ou bem cadastrado no TDNGo.</div>'}</section><section class="v6-section"><div class="v6-section-head"><h3>Materiais e peças utilizados</h3><span class="spacer"></span><button class="btn sm primary" onclick="v6OpenMaterial('${id}')">+ Registrar material</button></div><div>${mats.length?mats.map(materialHtml).join(''):'<div class="muted small">Nenhum material ou peça registrado.</div>'}</div>${mats.length?`<div class="v6-total">Custo informado: ${money(total)}</div>`:''}</section>${d.evaluation?`<section class="v6-section"><div class="v6-section-head"><h3>Avaliação do solicitante</h3></div><div><b>${d.evaluation.nota}/5</b> · ${d.evaluation.resolvido?'PROBLEMA RESOLVIDO':'PROBLEMA NÃO RESOLVIDO'}${d.evaluation.reaberto_pelo_solicitante?' · REABERTO PELO SOLICITANTE':''}</div>${d.evaluation.comentario?`<div class="small muted" style="margin-top:5px">${esc(d.evaluation.comentario)}</div>`:''}</section>`:''}`;body.append(...h.children);maskCpfIn(body)}catch(e){console.warn('[manut-v6 extras]',e)}}
window.v6OpenMaterial=function(id){$('action-title').textContent='Registrar material / peça';$('action-body').innerHTML=`<div class="grid"><div class="full"><label class="label">Descrição *</label><input id="v6-m-desc" class="input" maxlength="220" placeholder="EX.: TORNEIRA METÁLICA"></div><div><label class="label">Quantidade *</label><input id="v6-m-qtd" class="input" type="number" min="0.001" step="0.001" value="1"></div><div><label class="label">Unidade *</label><select id="v6-m-um"><option>UN</option><option>M</option><option>M²</option><option>KG</option><option>L</option><option>PCT</option><option>CX</option><option>PAR</option></select></div><div><label class="label">Origem</label><select id="v6-m-origem"><option>ESTOQUE</option><option>COMPRA</option><option>TERCEIRO</option><option>OUTRO</option></select></div><div><label class="label">Custo unitário (opcional)</label><input id="v6-m-custo" class="input" type="number" min="0" step="0.01" placeholder="0,00"></div><div class="full"><label class="label">Fornecedor (opcional)</label><input id="v6-m-forn" class="input" maxlength="180"></div><div class="full"><label class="label">Observação</label><textarea id="v6-m-obs" maxlength="500"></textarea></div></div>`;$('action-footer').innerHTML=`<button class="btn" onclick="closeModal('action-modal')">Cancelar</button><button class="btn primary" onclick="v6SaveMaterial('${id}')">Salvar material</button>`;$('action-modal').classList.add('open')}
window.v6SaveMaterial=async function(id){try{await api(EXT,'material_add',{id,descricao:$('v6-m-desc').value,quantidade:$('v6-m-qtd').value,unidade_medida:$('v6-m-um').value,origem:$('v6-m-origem').value,custo_unitario:$('v6-m-custo').value,fornecedor:$('v6-m-forn').value,observacao:$('v6-m-obs').value});window.closeModal?.('action-modal');toast('MATERIAL REGISTRADO.','ok');await injectExtras(id)}catch(e){toast(e.message,'err')}}
window.v6DeleteMaterial=async function(mid){if(!confirm('REMOVER ESTE MATERIAL DO CHAMADO?'))return;try{await api(EXT,'material_delete',{material_id:mid});toast('MATERIAL REMOVIDO.','ok');if(lastTicketId)await injectExtras(lastTicketId)}catch(e){toast(e.message,'err')}}
window.v6OpenAssetSearch=async function(id){try{lastTicket=(await detailMain(id)).ticket}catch{};$('action-title').textContent='Vincular patrimônio / equipamento';$('action-body').innerHTML=`<div class="notice">BUSQUE PELO CÓDIGO PATRIMONIAL, DESCRIÇÃO, FABRICANTE, MODELO OU NÚMERO DE SÉRIE. O SISTEMA SÓ PERMITE VINCULAR BENS DA MESMA UNIDADE DO CHAMADO.</div><div style="display:flex;gap:8px;margin-top:12px"><input id="v6-a-q" class="input" placeholder="EX.: 005398 OU MESA" style="flex:1"><button class="btn primary" onclick="v6SearchAsset('${id}')">Buscar</button></div><div id="v6-a-results" class="v6-search-results"></div>`;$('action-footer').innerHTML='<button class="btn" onclick="closeModal(\'action-modal\')">Fechar</button>';$('action-modal').classList.add('open');setTimeout(()=>$('v6-a-q')?.focus(),80)}
window.v6SearchAsset=async function(id){try{const d=await api(EXT,'asset_search',{unidade_id:lastTicket?.unidade_id||'',q:$('v6-a-q').value}),out=$('v6-a-results');out.innerHTML=d.data.length?d.data.map(a=>`<div class="v6-search-item"><div><b>${esc(a.codigo_patrimonio)} · ${esc(a.descricao)}</b><small>${esc([a.fabricante,a.modelo,a.numero_serie].filter(Boolean).join(' · ')||'SEM DADOS COMPLEMENTARES')}</small></div><button class="btn sm primary" onclick="v6LinkAsset('${id}','${a.id}')">Vincular</button></div>`).join(''):'<div class="muted small">Nenhum patrimônio encontrado.</div>'}catch(e){toast(e.message,'err')}}
window.v6LinkAsset=async function(id,pid){try{await api(EXT,'asset_link',{id,patrimonio_id:pid});window.closeModal?.('action-modal');toast('PATRIMÔNIO VINCULADO AO CHAMADO.','ok');await injectExtras(id)}catch(e){toast(e.message,'err')}}
window.v6UnlinkAsset=async function(id){if(!confirm('DESVINCULAR O PATRIMÔNIO DESTE CHAMADO?'))return;try{await api(EXT,'asset_link',{id,patrimonio_id:null});toast('VÍNCULO REMOVIDO.','ok');await injectExtras(id)}catch(e){toast(e.message,'err')}}
window.v6OriginAudit=async function(id){try{const d=await api(MAIN,'origin_audit',{id});$('action-title').textContent='Auditoria da origem';$('action-body').innerHTML=`<div class="v6-sensitive"><b>DADOS RESTRITOS À GESTÃO</b><div class="small" style="margin:4px 0 12px">ACESSO DESTINADO À APURAÇÃO, SEGURANÇA E AUDITORIA. EVITE REPRODUZIR ESTES DADOS EM OUTROS DOCUMENTOS.</div><div class="v6-sensitive-grid"><div><span>CPF</span><b>${esc(d.data.cpf||'—')}</b></div><div><span>Telefone</span><b>${esc(d.data.telefone||'—')}</b></div><div><span>IP</span><b>${esc(d.data.ip||'—')}</b></div><div><span>Navegador</span><b>${esc(d.data.user_agent||'—')}</b></div><div><span>Termo aceito em</span><b>${esc(d.data.termo_aceite_em?new Date(d.data.termo_aceite_em).toLocaleString('pt-BR'):'—')}</b></div><div><span>Localização</span><b>${d.data.geo?`${d.data.geo.lat}, ${d.data.geo.lng} · ±${Math.round(d.data.geo.accuracy||0)} m`:'NÃO COMPARTILHADA'}</b></div></div></div>`;$('action-footer').innerHTML='<button class="btn primary" onclick="closeModal(\'action-modal\')">Fechar</button>';$('action-modal').classList.add('open')}catch(e){toast(e.message,'err')}}
function addAuditButton(id){const f=$('detail-footer');if(!f||f.querySelector('.v6-audit-btn'))return;const s=sess();if(!s)return;const b=document.createElement('button');b.className='btn sm v6-audit-btn';b.textContent='Auditoria da origem';b.onclick=()=>window.v6OriginAudit(id);f.prepend(b)}
function wrapOpen(){if(wrappedOpen||typeof window.openTicket!=='function')return;wrappedOpen=true;const old=window.openTicket;window.openTicket=async function(id){lastTicketId=id;const r=await old(id);setTimeout(()=>{maskCpfIn($('detail-body')||document);injectExtras(id);addAuditButton(id)},160);return r}}
function surveyMarkup(proto,token,evalData){if(evalData)return `<div class="v6-survey"><b>AVALIAÇÃO REGISTRADA</b><div style="margin-top:6px">NOTA ${evalData.nota}/5 · ${evalData.resolvido?'PROBLEMA RESOLVIDO':'PROBLEMA NÃO RESOLVIDO'}${evalData.reaberto_pelo_solicitante?' · CHAMADO REABERTO':''}</div>${evalData.comentario?`<div class="small" style="margin-top:6px">${esc(evalData.comentario)}</div>`:''}</div>`;return `<div class="v6-survey" data-proto="${esc(proto)}" data-token="${esc(token)}"><b>COMO FOI O ATENDIMENTO?</b><div class="small muted">SUA AVALIAÇÃO AJUDA A MEDIR QUALIDADE, REINCIDÊNCIA E EFETIVIDADE DA MANUTENÇÃO.</div><div class="v6-stars">${[1,2,3,4,5].map(n=>`<button type="button" onclick="v6SurveyStar(this,${n})">${n}</button>`).join('')}</div><div class="v6-choice"><button type="button" class="btn" onclick="v6SurveyResolved(this,true)">Problema resolvido</button><button type="button" class="btn" onclick="v6SurveyResolved(this,false)">Não resolvido</button></div><textarea id="v6-survey-comment" maxlength="1200" placeholder="COMENTÁRIO OPCIONAL"></textarea><label id="v6-reopen-wrap" class="consent hide" style="margin-top:8px"><input id="v6-reopen" type="checkbox" checked><span>REABRIR ESTE CHAMADO PARA NOVO ATENDIMENTO.</span></label><div class="v6-reopen-note hide" id="v6-reopen-note">A REABERTURA PELO SOLICITANTE FICA DISPONÍVEL POR ATÉ 30 DIAS APÓS A CONCLUSÃO.</div><button type="button" class="btn primary" style="margin-top:10px" onclick="v6SubmitSurvey()">Enviar avaliação</button></div>`}
let surveyScore=0,surveyResolved=null;
window.v6SurveyStar=function(btn,n){surveyScore=n;btn.parentElement.querySelectorAll('button').forEach((b,i)=>b.classList.toggle('active',i<n))}
window.v6SurveyResolved=function(btn,v){surveyResolved=v;btn.parentElement.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===btn));$('v6-reopen-wrap')?.classList.toggle('hide',v);$('v6-reopen-note')?.classList.toggle('hide',v)}
window.v6SubmitSurvey=async function(){const box=document.querySelector('.v6-survey[data-proto]');if(!box||!surveyScore||surveyResolved===null)return toast('INFORME A NOTA E SE O PROBLEMA FOI RESOLVIDO.','err');try{const d=await api(EXT,'survey_submit',{protocolo:box.dataset.proto,token:box.dataset.token,nota:surveyScore,resolvido:surveyResolved,comentario:$('v6-survey-comment')?.value||'',reabrir:!surveyResolved&&!!$('v6-reopen')?.checked},false);toast(d.reopened?'CHAMADO REABERTO E GESTÃO NOTIFICADA.':'AVALIAÇÃO REGISTRADA.','ok');await renderSurvey()}catch(e){toast(e.message,'err')}}
async function renderSurvey(){const out=$('track-result'),proto=$('track-protocol')?.value,token=$('track-token')?.value;if(!out||!proto||!token)return;out.querySelectorAll('.v6-survey').forEach(x=>x.remove());try{const d=await api(EXT,'survey_get',{protocolo:proto,token},false);if(d.status==='CONCLUIDO'||d.evaluation){out.insertAdjacentHTML('beforeend',surveyMarkup(proto,token,d.evaluation));maskCpfIn(out)}}catch{}}
function wrapTrack(){if(wrappedTrack||typeof window.trackPublic!=='function')return;wrappedTrack=true;const old=window.trackPublic;window.trackPublic=async function(){surveyScore=0;surveyResolved=null;const r=await old();setTimeout(renderSurvey,120);return r}}
function markCritical(){document.querySelectorAll('[class*=pill]').forEach(p=>{if(['P1','P2'].includes((p.textContent||'').trim()))p.classList.add('v6-badge-critical')})}
function init(){
 window.enableNotifications=enablePush;
 const css=document.createElement('link');if(!document.querySelector('link[href*="manutencao-v6.css"]')){css.rel='stylesheet';css.href='manutencao-v6.css?v=20260914-0110';document.head.appendChild(css)}
 let tries=0;const t=setInterval(()=>{tries++;wrapOpen();wrapTrack();decoratePush();markCritical();maskCpfIn();if(wrappedOpen&&wrappedTrack||tries>120)clearInterval(t)},100);
 const mo=new MutationObserver(ms=>{let useful=false;for(const m of ms)for(const n of m.addedNodes)if(n.nodeType===1){useful=true;maskCpfIn(n);markCritical()}if(useful)decoratePush()});mo.observe(document.body,{childList:true,subtree:true});
 setTimeout(ensurePush,2500);
 const q=new URLSearchParams(location.search);if(q.get('ticket'))setTimeout(()=>window.openTicket?.(q.get('ticket')),1800)
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();