const CACHE='tdngo-manut-v6-20260913-alerts';
const SHELL=['./manutencao.html','./manutencao-v3.css','./manutencao-v4.css','./manutencao-v5.css','./manutencao-app.js','./manutencao-ui-v3.js','./manutencao-ui-v4.js','./manutencao-ui-v5.js','./manutencao-chamado.html','./manutencao.webmanifest','./assets/manutencao-icon.svg'];
function enhanceHtml(html){if(!html)return html;if(!html.includes('manutencao-v4.css'))html=html.replace('</head>','<link rel="stylesheet" href="manutencao-v4.css?v=20260913-2256"></head>');if(!html.includes('manutencao-v5.css'))html=html.replace('</head>','<link rel="stylesheet" href="manutencao-v5.css?v=20260913-2315"></head>');if(!html.includes('manutencao-ui-v4.js'))html=html.replace('</body>','<script src="manutencao-ui-v4.js?v=20260913-2256"><\/script></body>');if(!html.includes('manutencao-ui-v5.js'))html=html.replace('</body>','<script src="manutencao-ui-v5.js?v=20260913-2315"><\/script></body>');return html}
function htmlResponse(text,base){const h=new Headers(base.headers);h.delete('content-length');h.delete('content-encoding');h.set('content-type','text/html; charset=utf-8');h.set('cache-control','no-store');return new Response(text,{status:base.status,statusText:base.statusText,headers:h})}
async function navResponse(req){try{const net=await fetch(req,{cache:'no-store'});if(!net.ok)return net;let out=net;if(new URL(req.url).pathname.endsWith('/manutencao.html'))out=htmlResponse(enhanceHtml(await net.text()),net);const cp=out.clone();caches.open(CACHE).then(c=>c.put(req,cp)).catch(()=>{});return out}catch{const cached=await caches.match(req)||await caches.match('./manutencao.html');if(!cached)return new Response('Sem conexão.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});if(new URL(req.url).pathname.endsWith('/manutencao.html'))return htmlResponse(enhanceHtml(await cached.text()),cached);return cached}}
async function assetResponse(req){try{const net=await fetch(req,{cache:'no-store'});if(net&&net.ok){const cp=net.clone();caches.open(CACHE).then(c=>c.put(req,cp)).catch(()=>{})}return net}catch{return (await caches.match(req))||new Response('',{status:504})}}
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).catch(()=>{}));self.skipWaiting()});
self.addEventListener('activate',e=>{e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('tdngo-manut-')&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim();const ws=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const w of ws){try{const u=new URL(w.url);if(u.pathname.endsWith('/manutencao.html'))await w.navigate(w.url)}catch{}}})())});
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const u=new URL(r.url);if(u.origin!==location.origin)return;if(r.mode==='navigate'){e.respondWith(navResponse(r));return}if(/\.(?:js|css)$/.test(u.pathname)){e.respondWith(assetResponse(r));return}e.respondWith(caches.match(r).then(cached=>{const net=fetch(r).then(resp=>{if(resp&&resp.ok){const cp=resp.clone();caches.open(CACHE).then(c=>c.put(r,cp)).catch(()=>{})}return resp}).catch(()=>cached);return cached||net}))});
self.addEventListener('message',e=>{if(e.data==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('notificationclick',e=>{e.notification.close();const target=e.notification?.data?.url||'./manutencao.html?go=alerts';e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(ws=>{for(const w of ws){try{if('navigate'in w)w.navigate(target)}catch{}if('focus'in w)return w.focus()}return clients.openWindow(target)}))});
