const CACHE='tdngo-manut-v4-20260913b';
const SHELL=['./manutencao.html','./manutencao-v3.css','./manutencao-v4.css','./manutencao-app.js','./manutencao-ui-v3.js','./manutencao-ui-v4.js','./manutencao-chamado.html','./manutencao.webmanifest','./assets/manutencao-icon.svg'];
function enhanceHtml(html){if(!html||html.includes('manutencao-ui-v4.js'))return html;html=html.replace('</head>','<link rel="stylesheet" href="manutencao-v4.css?v=20260913-1815"></head>');html=html.replace('</body>','<script src="manutencao-ui-v4.js?v=20260913-1815"><\/script></body>');return html}
function htmlResponse(text,base){const h=new Headers(base.headers);h.delete('content-length');h.delete('content-encoding');h.set('content-type','text/html; charset=utf-8');h.set('cache-control','no-store');return new Response(text,{status:base.status,statusText:base.statusText,headers:h})}
async function navResponse(req){try{const net=await fetch(req,{cache:'no-store'});if(!net.ok)return net;let out=net;if(new URL(req.url).pathname.endsWith('/manutencao.html'))out=htmlResponse(enhanceHtml(await net.text()),net);const cp=out.clone();caches.open(CACHE).then(c=>c.put(req,cp)).catch(()=>{});return out}catch{const cached=await caches.match(req)||await caches.match('./manutencao.html');if(!cached)return new Response('Sem conexão.',{status:503,headers:{'Content-Type':'text/plain; charset=utf-8'}});if(new URL(req.url).pathname.endsWith('/manutencao.html'))return htmlResponse(enhanceHtml(await cached.text()),cached);return cached}}
self.addEventListener('install',e=>{e.waitUntil(caches.open(CACHE).then(c=>c.addAll(SHELL)).catch(()=>{}));self.skipWaiting()});
self.addEventListener('activate',e=>{e.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('tdngo-manut-')&&k!==CACHE).map(k=>caches.delete(k)));await self.clients.claim();const ws=await self.clients.matchAll({type:'window',includeUncontrolled:true});for(const w of ws){try{const u=new URL(w.url);if(u.pathname.endsWith('/manutencao.html'))await w.navigate(w.url)}catch{}}})())});
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const u=new URL(r.url);if(u.origin!==location.origin)return;if(r.mode==='navigate'){e.respondWith(navResponse(r));return}e.respondWith(caches.match(r).then(cached=>{const net=fetch(r).then(resp=>{if(resp&&resp.ok){const cp=resp.clone();caches.open(CACHE).then(c=>c.put(r,cp)).catch(()=>{})}return resp}).catch(()=>cached);return cached||net}))});
self.addEventListener('message',e=>{if(e.data==='SKIP_WAITING')self.skipWaiting()});
self.addEventListener('notificationclick',e=>{e.notification.close();e.waitUntil(clients.matchAll({type:'window',includeUncontrolled:true}).then(ws=>{for(const w of ws){if('focus'in w)return w.focus()}return clients.openWindow('./manutencao.html?go=field')}))});
