(()=>{
'use strict';
const SIX=/^\d{6}$/;
let audioCtx=null,lastFeedback='',lastFeedbackAt=0;
let invStream=null,invVideo=null,invCanvas=null,invCtx=null,invRaf=0,invBusy=false,invLast='',invLastAt=0,invSessionCount=0,invCurrent=null;

function css(){if(document.getElementById('pat-flow-v9'))return;const s=document.createElement('style');s.id='pat-flow-v9';s.textContent=`
.pm-alert-stack{position:fixed;z-index:12000;top:max(14px,env(safe-area-inset-top));left:50%;transform:translateX(-50%);width:min(430px,calc(100vw - 24px));display:grid;gap:8px;pointer-events:none}.pm-alert{pointer-events:auto;background:color-mix(in srgb,var(--pm-surface,#121922) 96%,transparent);color:var(--pm-text,#edf2f7);border:1px solid var(--pm-border,#26313d);border-radius:14px;box-shadow:0 16px 45px rgba(0,0,0,.26);padding:12px;display:grid;grid-template-columns:36px 1fr auto;gap:10px;align-items:center;backdrop-filter:blur(18px);animation:pmIn .18s ease-out}.pm-alert.success{border-color:rgba(34,197,94,.35)}.pm-alert.warn{border-color:rgba(245,158,11,.4)}.pm-alert.error{border-color:rgba(239,68,68,.42)}.pm-alert-icon{width:36px;height:36px;border-radius:11px;display:grid;place-items:center;font-size:18px;background:rgba(59,130,246,.12);color:#60a5fa}.pm-alert.success .pm-alert-icon{background:rgba(34,197,94,.12);color:#4ade80}.pm-alert.warn .pm-alert-icon{background:rgba(245,158,11,.13);color:#fbbf24}.pm-alert.error .pm-alert-icon{background:rgba(239,68,68,.13);color:#fb7185}.pm-alert-copy b{display:block;font-size:12px}.pm-alert-copy span{display:block;color:var(--pm-muted,#8b99aa);font-size:10px;margin-top:2px;line-height:1.35}.pm-alert-actions{display:flex;gap:5px}.pm-alert-actions button{border:0;border-radius:9px;padding:8px 10px;background:var(--pm-accent,#2367d1);color:#fff;font:700 10px system-ui}.pm-alert-actions button.ghost{background:var(--pm-surface2,#18212c);color:var(--pm-text,#edf2f7);border:1px solid var(--pm-border,#26313d)}@keyframes pmIn{from{opacity:0;transform:translateY(-8px) scale(.98)}to{opacity:1;transform:none}}
.pm-inv-live{margin-top:12px}.pm-inv-camera{height:280px;border-radius:14px;overflow:hidden;background:#05080c;border:1px solid var(--pm-border,#26313d);position:relative}.pm-inv-camera video{width:100%;height:100%;object-fit:cover;display:block}.pm-inv-camera:after{content:'';position:absolute;inset:16% 12%;border:2px solid rgba(255,255,255,.92);border-radius:15px;box-shadow:0 0 0 999px rgba(0,0,0,.12);pointer-events:none}.pm-inv-strip{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-top:8px}.pm-inv-stat{border:1px solid var(--pm-border,#26313d);background:var(--pm-surface2,#18212c);border-radius:10px;padding:9px}.pm-inv-stat b{display:block;font-size:17px}.pm-inv-stat span{display:block;font-size:8px;color:var(--pm-muted,#8b99aa);margin-top:2px}.pm-inv-recent{margin-top:9px;display:grid;gap:5px;max-height:150px;overflow:auto}.pm-inv-row{display:grid;grid-template-columns:auto 1fr auto;gap:8px;align-items:center;border:1px solid var(--pm-border,#26313d);border-radius:9px;padding:8px 9px;background:var(--pm-surface2,#18212c);font-size:10px}.pm-inv-row strong{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;color:var(--pm-accent2,#60a5fa)}.pm-inv-row small{color:var(--pm-muted,#8b99aa)}.pm-inv-row .ok{color:#4ade80}.pm-inv-row .dup{color:#fbbf24}.pm-inv-row .bad{color:#fb7185}.pm-inv-live-note{font-size:9px;color:var(--pm-muted,#8b99aa);text-align:center;margin-top:7px}
@media(max-width:760px){.pm-alert-stack{top:max(72px,calc(env(safe-area-inset-top) + 62px))}.pm-alert{grid-template-columns:34px 1fr;padding:10px}.pm-alert-actions{grid-column:1/-1;justify-content:flex-end}.pm-inv-camera{height:min(45dvh,360px)}#invscan-modal .modal-b{padding-top:10px!important}.pm-inv-strip{position:sticky;top:0;z-index:2}}
`;
document.head.appendChild(s)}

function ensureAlertStack(){let x=document.querySelector('.pm-alert-stack');if(!x){x=document.createElement('div');x.className='pm-alert-stack';document.body.appendChild(x)}return x}
function alertModern(type,title,text,actions=[],ttl=1700){const stack=ensureAlertStack(),el=document.createElement('div');el.className='pm-alert '+type;const icon=type==='success'?'✓':type==='warn'?'!':type==='error'?'×':'i';el.innerHTML=`<div class="pm-alert-icon">${icon}</div><div class="pm-alert-copy"><b>${escapeHtml(title)}</b><span>${escapeHtml(text||'')}</span></div><div class="pm-alert-actions"></div>`;const a=el.querySelector('.pm-alert-actions');actions.forEach((x,i)=>{const b=document.createElement('button');b.textContent=x.label;b.className=x.ghost?'ghost':'';b.onclick=()=>{x.action?.();el.remove()};a.appendChild(b)});stack.appendChild(el);if(!actions.length&&ttl)setTimeout(()=>el.remove(),ttl);return el}
function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function beep(kind='ok'){
 try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain(),now=audioCtx.currentTime;o.type='sine';o.frequency.setValueAtTime(kind==='dup'?560:kind==='bad'?330:960,now);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(kind==='ok'?.12:.08,now+.008);g.gain.exponentialRampToValueAtTime(.0001,now+(kind==='ok'?.075:.11));o.connect(g);g.connect(audioCtx.destination);o.start(now);o.stop(now+.13)}catch(e){}
}
function feedbackOnce(code,type,title,text){const now=Date.now(),key=type+'|'+code;if(key===lastFeedback&&now-lastFeedbackAt<700)return;lastFeedback=key;lastFeedbackAt=now;beep(type==='success'?'ok':type==='warn'?'dup':'bad');if(navigator.vibrate)navigator.vibrate(type==='success'?45:[35,30,35]);alertModern(type,title,text)}

window.pmRegisterScanned=function(code,fromInventory=false){
 code=String(code||'').replace(/\D/g,'').slice(0,6);if(!SIX.test(code))return;
 try{window.stopScanner?.()}catch(e){}
 if(fromInventory)stopInvCamera();
 if(typeof openAsset==='function')openAsset();
 setTimeout(()=>{const input=document.getElementById('a-code');if(input){input.value=code;input.dispatchEvent(new Event('input',{bubbles:true}));input.focus()}const title=document.getElementById('asset-modal-title');if(title)title.textContent='Cadastrar patrimônio '+code},80);
};

function watchScanner(){const out=document.getElementById('scan-result');if(!out)return;new MutationObserver(()=>{
 const code=(out.querySelector('.asset-code')?.textContent||document.getElementById('scan-code')?.value||'').trim();
 if(out.querySelector('.asset-code')&&SIX.test(code)){const desc=out.querySelector('.asset-title')?.textContent||'Patrimônio localizado';feedbackOnce(code,'success','Patrimônio localizado',code+' · '+desc);return}
 const txt=(out.textContent||'').toLowerCase();if(SIX.test(code)&&(txt.includes('não localizado')||txt.includes('não cadastrado')||txt.includes('nao localizado')||txt.includes('nao cadastrado'))){beep('bad');try{window.stopScanner?.()}catch(e){}alertModern('error','QR não cadastrado','O patrimônio '+code+' não foi localizado na base.',[{label:'Agora não',ghost:true,action:()=>setTimeout(()=>window.startScanner?.(),120)},{label:'Cadastrar',action:()=>pmRegisterScanned(code,false)}],0)}
 }).observe(out,{childList:true,subtree:true,characterData:true})}

function loadJsQR(){if(window.jsQR)return Promise.resolve();return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
async function stopInvCamera(){if(invRaf){cancelAnimationFrame(invRaf);invRaf=0}if(invStream){invStream.getTracks().forEach(t=>t.stop());invStream=null}if(invVideo){try{invVideo.srcObject=null}catch(e){}invVideo=null}}
async function startInvCamera(){
 const host=document.querySelector('#invscan-modal .pm-inv-camera');if(!host||invStream)return;
 try{await loadJsQR();host.innerHTML='';invVideo=document.createElement('video');invVideo.playsInline=true;invVideo.muted=true;invVideo.autoplay=true;host.appendChild(invVideo);invStream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:30,max:60}}});invVideo.srcObject=invStream;await invVideo.play();try{const tr=invStream.getVideoTracks()[0],caps=tr.getCapabilities?.()||{},adv={};if(Array.isArray(caps.focusMode)&&caps.focusMode.includes('continuous'))adv.focusMode='continuous';if(Object.keys(adv).length)await tr.applyConstraints({advanced:[adv]})}catch(e){}invCanvas=document.createElement('canvas');invCtx=invCanvas.getContext('2d',{willReadFrequently:true});scanInvFrame()}catch(e){host.innerHTML='<div class="empty">Não foi possível abrir a câmera. Use o código manual.</div>'}
}
function scanInvFrame(){if(!invVideo||!invCtx||!window.jsQR){invRaf=requestAnimationFrame(scanInvFrame);return}if(invVideo.readyState>=2){const vw=invVideo.videoWidth,vh=invVideo.videoHeight;if(vw&&vh){const scale=Math.min(1,900/vw),w=Math.floor(vw*scale),h=Math.floor(vh*scale);if(invCanvas.width!==w||invCanvas.height!==h){invCanvas.width=w;invCanvas.height=h}invCtx.drawImage(invVideo,0,0,w,h);try{const d=invCtx.getImageData(0,0,w,h),q=window.jsQR(d.data,w,h,{inversionAttempts:'attemptBoth'});const code=String(q?.data||'').trim();if(SIX.test(code))processInvCode(code)}catch(e){}}}invRaf=requestAnimationFrame(scanInvFrame)}
function invRecent(code,label,kind='ok'){const list=document.querySelector('.pm-inv-recent');if(!list)return;const row=document.createElement('div');row.className='pm-inv-row';row.innerHTML=`<strong>${escapeHtml(code)}</strong><span>${escapeHtml(label)}</span><small class="${kind}">${kind==='ok'?'CONFIRMADO':kind==='dup'?'REPETIDO':'PENDÊNCIA'}</small>`;list.prepend(row);while(list.children.length>6)list.lastElementChild.remove()}
function updateInvStats(){const n=document.getElementById('pm-inv-session');if(n)n.textContent=invSessionCount}
async function processInvCode(code){const now=Date.now();if(invBusy||(code===invLast&&now-invLastAt<800))return;invBusy=true;invLast=code;invLastAt=now;const inp=document.getElementById('is-code');if(inp)inp.value=code;try{const r=await post({action:'inventory_scan',inventario_id:document.getElementById('is-id').value,codigo:code});if(r.ja_encontrado){beep('dup');if(navigator.vibrate)navigator.vibrate(30);alertModern('warn','Já conferido',code+' já havia sido registrado.');invRecent(code,r.data?.descricao||'Patrimônio já conferido','dup')}else{invSessionCount++;updateInvStats();beep('ok');if(navigator.vibrate)navigator.vibrate(45);alertModern('success','Conferido',code+' · '+(r.data?.descricao||''));invRecent(code,r.data?.descricao||'Patrimônio confirmado','ok')}if(inp)inp.value=''}catch(e){const msg=String(e?.message||e),missing=/não cadastrado|nao cadastrado|não localizado|nao localizado/i.test(msg);beep('bad');if(missing){await stopInvCamera();invRecent(code,'Não cadastrado na base','bad');alertModern('error','QR não cadastrado','O patrimônio '+code+' não existe na base. Você pode cadastrá-lo agora.',[{label:'Continuar',ghost:true,action:()=>setTimeout(startInvCamera,150)},{label:'Cadastrar',action:()=>pmRegisterScanned(code,true)}],0)}else{alertModern('error','Não foi possível conferir',msg);invRecent(code,msg,'bad')}}finally{setTimeout(()=>invBusy=false,120)}}

function enhanceInventory(){
 const oldOpen=window.openInventoryScan;if(typeof oldOpen==='function')window.openInventoryScan=function(js){try{window.stopScanner?.()}catch(e){}oldOpen.apply(this,arguments);let data={};try{data=JSON.parse(js)}catch(e){}invCurrent=data;invSessionCount=0;setTimeout(()=>{const modal=document.getElementById('invscan-modal'),body=modal?.querySelector('.modal-b');if(!body)return;let live=body.querySelector('.pm-inv-live');if(!live){live=document.createElement('div');live.className='pm-inv-live';live.innerHTML=`<div class="pm-inv-camera"><div class="empty">Iniciando câmera...</div></div><div class="pm-inv-strip"><div class="pm-inv-stat"><b id="pm-inv-session">0</b><span>Lidos nesta sessão</span></div><div class="pm-inv-stat"><b>6 dígitos</b><span>Padrão QR</span></div><div class="pm-inv-stat"><b>Contínuo</b><span>Pronto para o próximo</span></div></div><div class="pm-inv-live-note">Aponte para as etiquetas em sequência. Não é necessário tocar em Confirmar.</div><div class="pm-inv-recent"></div>`;body.insertBefore(live,body.querySelector('.scan-manual'))}else{live.querySelector('.pm-inv-recent').innerHTML='';updateInvStats()}startInvCamera()},100)};
 const oldManual=window.inventoryScan;if(typeof oldManual==='function')window.inventoryScan=function(){const code=String(document.getElementById('is-code')?.value||'').replace(/\D/g,'').slice(0,6);if(!SIX.test(code)){alertModern('warn','Código incompleto','Informe os 6 dígitos do patrimônio.');return}processInvCode(code)};
 const modal=document.getElementById('invscan-modal');if(modal)new MutationObserver(()=>{if(!modal.classList.contains('open')){stopInvCamera();if(typeof loadInventories==='function')loadInventories()}}).observe(modal,{attributes:true,attributeFilter:['class']})
}

function install(){css();watchScanner();enhanceInventory();document.addEventListener('pointerdown',()=>{try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume()}catch(e){}},{once:true,capture:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,1100));else setTimeout(install,1100);
})();