(()=>{
'use strict';

const ICON={
 back:'<svg viewBox="0 0 24 24"><path d="M15 18l-6-6 6-6"/></svg>',
 home:'<svg viewBox="0 0 24 24"><path d="M4 11.5 12 5l8 6.5V20h-5v-5H9v5H4z"/></svg>',
 asset:'<svg viewBox="0 0 24 24"><rect x="4" y="6" width="16" height="13" rx="2"/><path d="M8 6V4h8v2M8 11h8M8 15h5"/></svg>',
 qr:'<svg viewBox="0 0 24 24"><path d="M8 3H5a2 2 0 0 0-2 2v3M16 3h3a2 2 0 0 1 2 2v3M8 21H5a2 2 0 0 1-2-2v-3M16 21h3a2 2 0 0 0 2-2v-3"/><rect x="8" y="8" width="3" height="3"/><rect x="13" y="8" width="3" height="3"/><rect x="8" y="13" width="3" height="3"/><path d="M14 14h2v2h-2z"/></svg>',
 inventory:'<svg viewBox="0 0 24 24"><path d="M7 4h10a2 2 0 0 1 2 2v15H5V6a2 2 0 0 1 2-2z"/><path d="M9 4V2.8h6V4M8 10h8M8 14h8M8 18h5"/></svg>',
 wrench:'<svg viewBox="0 0 24 24"><path d="M14.5 6.5a4.5 4.5 0 0 0-5.8 5.8L4 17l3 3 4.7-4.7a4.5 4.5 0 0 0 5.8-5.8l-3 3-3-3z"/></svg>',
 chart:'<svg viewBox="0 0 24 24"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>',
 gear:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.6-2-3.4-2.5 1a8 8 0 0 0-1.7-1L14.3 3h-4.6l-.4 3a8 8 0 0 0-1.7 1l-2.5-1-2 3.4 2 1.6a7 7 0 0 0 0 2l-2 1.6 2 3.4 2.5-1a8 8 0 0 0 1.7 1l.4 3h4.6l.4-3a8 8 0 0 0 1.7-1l2.5 1 2-3.4-2-1.6a7 7 0 0 0 .1-1z"/></svg>',
 upload:'<svg viewBox="0 0 24 24"><path d="M12 16V4M8 8l4-4 4 4M5 20h14"/></svg>',
 more:'<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1.3"/><circle cx="12" cy="12" r="1.3"/><circle cx="19" cy="12" r="1.3"/></svg>',
 plus:'<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>',
 close:'<svg viewBox="0 0 24 24"><path d="m6 6 12 12M18 6 6 18"/></svg>'
};

const PAGE={
 dashboard:{label:'Visão geral',short:'Início',icon:ICON.home},
 bens:{label:'Bens patrimoniais',short:'Bens',icon:ICON.asset},
 scanner:{label:'Escanear QR',short:'QR',icon:ICON.qr},
 inventario:{label:'Inventários',short:'Inventário',icon:ICON.inventory},
 manutencao:{label:'Manutenção clínica',short:'Manutenção',icon:ICON.wrench},
 relatorios:{label:'Relatórios',short:'Relatórios',icon:ICON.chart},
 config:{label:'Configurações',short:'Config.',icon:ICON.gear},
 importacao:{label:'Importação inicial',short:'Importar',icon:ICON.upload}
};

function addCss(){
 const old=document.getElementById('pat-ui-v22');if(old)old.remove();
 const s=document.createElement('style');s.id='pat-ui-v22';s.textContent=`
 :root{--ui-bg:#0c1118;--ui-surface:#121923;--ui-surface2:#18212d;--ui-border:#263241;--ui-text:#edf3f8;--ui-muted:#8c9aaa;--ui-primary:#2f81f7;--ui-primary-soft:#142a45;--ui-success:#3fb950;--ui-danger:#f85149;--ui-warning:#d29922;--ui-radius:14px;--ui-shadow:0 14px 40px rgba(0,0,0,.18)}
 body[data-theme="light"]{--ui-bg:#f4f7fa;--ui-surface:#fff;--ui-surface2:#f7f9fb;--ui-border:#dde4eb;--ui-text:#18222d;--ui-muted:#667585;--ui-primary:#1769d2;--ui-primary-soft:#eaf3ff;--ui-shadow:0 12px 30px rgba(28,39,49,.08)}
 html,body{background:var(--ui-bg)!important;color:var(--ui-text)!important}
 body{font-size:13px!important}
 .app{min-height:100dvh!important;display:flex!important;background:var(--ui-bg)!important}
 .side{width:224px!important;position:fixed!important;inset:0 auto 0 0!important;padding:14px 12px!important;background:var(--ui-surface)!important;border-right:1px solid var(--ui-border)!important;overflow:auto!important;z-index:1100!important}
 .main{margin-left:224px!important;width:calc(100% - 224px)!important;max-width:none!important;padding:24px 28px 40px!important;min-width:0!important}
 .brand{display:flex!important;align-items:center!important;gap:10px!important;padding:4px 4px 16px!important;margin:0 0 12px!important;border-bottom:1px solid var(--ui-border)!important}
 .brand .ico{width:36px!important;height:36px!important;border-radius:11px!important;background:var(--ui-primary)!important;color:#fff!important;display:grid!important;place-items:center!important;font-size:0!important;flex:0 0 auto!important}.brand .ico svg{width:19px;height:19px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}
 .brand b{font-size:13px!important;color:var(--ui-text)!important}.brand span{font-size:9px!important;color:var(--ui-muted)!important;margin-top:2px!important}
 .nav{display:grid!important;gap:3px!important}.nav button{width:100%!important;min-height:42px!important;margin:0!important;padding:0 10px!important;border:0!important;border-radius:10px!important;background:transparent!important;color:var(--ui-muted)!important;display:flex!important;align-items:center!important;gap:10px!important;text-align:left!important;font-size:11px!important;font-weight:650!important;transition:background .12s ease,color .12s ease!important}.nav button:hover{background:var(--ui-surface2)!important;color:var(--ui-text)!important}.nav button.active{background:var(--ui-primary-soft)!important;color:var(--ui-primary)!important}.nav button .ui-nav-icon{width:20px;height:20px;display:grid;place-items:center;flex:0 0 20px}.nav button .ui-nav-icon svg{width:19px;height:19px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.nav button .ui-nav-label{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}
 .side-foot{margin-top:14px!important;padding-top:12px!important;border-top:1px solid var(--ui-border)!important}.side-foot button{width:100%!important;min-height:40px!important;border:1px solid var(--ui-border)!important;border-radius:10px!important;background:var(--ui-surface2)!important;color:var(--ui-text)!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;gap:8px!important;padding:0 10px!important;font-size:10px!important;font-weight:700!important}.side-foot button svg{width:17px;height:17px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}
 .page{max-width:1520px!important;margin:0 auto!important}.top{display:flex!important;align-items:flex-start!important;justify-content:space-between!important;gap:18px!important;margin:0 0 18px!important}.top h1,.pm-health-section-title h1,.inv15-head h1{font-size:24px!important;letter-spacing:-.45px!important;font-weight:780!important;color:var(--ui-text)!important;margin:0!important}.top p,.pm-health-section-title p,.inv15-head p{color:var(--ui-muted)!important;font-size:11px!important;margin:5px 0 0!important}
 .card,.pm-health-card,.inv15-card,.inv15-kpi,.pm-hk{background:var(--ui-surface)!important;border:1px solid var(--ui-border)!important;border-radius:var(--ui-radius)!important;box-shadow:none!important;color:var(--ui-text)!important}.card{padding:14px!important}
 .grid4,.pm-health-kpis{gap:10px!important}.stat{min-height:98px!important;padding:14px!important}.stat .num{font-size:24px!important;letter-spacing:-.5px!important}.stat .lbl{font-size:8.5px!important;color:var(--ui-muted)!important;margin-top:8px!important}
 .btn{min-height:36px!important;border-radius:10px!important;border:1px solid var(--ui-border)!important;background:var(--ui-surface)!important;color:var(--ui-text)!important;padding:7px 11px!important;box-shadow:none!important;font-size:10px!important;font-weight:700!important}.btn:hover{background:var(--ui-surface2)!important}.btn.primary{background:var(--ui-primary)!important;border-color:var(--ui-primary)!important;color:#fff!important}.btn.red{background:transparent!important;border-color:rgba(248,81,73,.4)!important;color:#ff817a!important}.btn.green{background:#238636!important;border-color:#238636!important;color:#fff!important}
 input,select,textarea,.inv16-search,.inv16-filter{background:var(--ui-surface)!important;color:var(--ui-text)!important;border:1px solid var(--ui-border)!important;border-radius:10px!important;padding:8px 10px!important;box-shadow:none!important;outline:none!important}input:focus,select:focus,textarea:focus{border-color:var(--ui-primary)!important;box-shadow:0 0 0 3px color-mix(in srgb,var(--ui-primary) 13%,transparent)!important}
 .toolbar,.pm-health-toolbar{display:flex!important;align-items:center!important;gap:8px!important;flex-wrap:wrap!important;margin-bottom:12px!important}.toolbar input,.pm-health-toolbar input{flex:1!important;min-width:250px!important;min-height:38px!important}.toolbar select,.pm-health-toolbar select{min-height:38px!important}
 .table,.pm-health-table{border:1px solid var(--ui-border)!important;border-radius:12px!important;background:var(--ui-surface)!important;overflow:auto!important;box-shadow:none!important}.table table,.pm-health-table table{width:100%!important;border-collapse:collapse!important}.table th,.pm-health-table th{background:var(--ui-surface2)!important;color:var(--ui-muted)!important;font-size:8.5px!important;text-transform:uppercase!important;letter-spacing:.05em!important;padding:10px 11px!important;border-bottom:1px solid var(--ui-border)!important}.table td,.pm-health-table td{font-size:10.5px!important;padding:11px!important;border-bottom:1px solid var(--ui-border)!important;color:var(--ui-text)!important}.table tbody tr:last-child td,.pm-health-table tbody tr:last-child td{border-bottom:0!important}.table tbody tr:hover,.pm-health-table tbody tr:hover{background:color-mix(in srgb,var(--ui-primary) 3%,transparent)!important}
 .pill{border-radius:999px!important;padding:4px 7px!important;font-size:8px!important;font-weight:800!important;background:var(--ui-primary-soft)!important;color:var(--ui-primary)!important}.pill.ok{background:rgba(63,185,80,.12)!important;color:#54cf68!important}.pill.warn{background:rgba(210,153,34,.14)!important;color:#e3b341!important}.pill.bad{background:rgba(248,81,73,.13)!important;color:#ff7b72!important}
 .scanner-box{max-width:820px!important}.scan-frame{background:#02060b!important;border:1px solid var(--ui-border)!important;border-radius:18px!important;min-height:390px!important}.scan-manual{gap:8px!important}.scan-manual input{min-height:46px!important;border-radius:12px!important}.pm-scan-clear{min-height:42px!important;border-radius:11px!important;background:var(--ui-primary-soft)!important;border:1px solid color-mix(in srgb,var(--ui-primary) 35%,var(--ui-border))!important;color:var(--ui-primary)!important}
 #p-inventario{max-width:1520px!important}.inv15-head{align-items:center!important;margin-bottom:16px!important}.inv15-grid{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:10px!important}.inv15-card{padding:14px!important}.inv15-progress{height:7px!important;background:var(--ui-surface2)!important;border-radius:999px!important;overflow:hidden!important}.inv15-progress i{background:var(--ui-primary)!important}.inv15-stats{display:grid!important;grid-template-columns:repeat(3,1fr)!important;gap:6px!important}.inv15-stat{background:var(--ui-surface2)!important;border-radius:10px!important;padding:8px!important}.inv15-stat span{color:var(--ui-muted)!important}.inv15-actions{display:flex!important;gap:6px!important}.inv15-sheet{background:var(--ui-bg)!important;border:1px solid var(--ui-border)!important;border-radius:18px!important}.inv15-sheet-h{background:color-mix(in srgb,var(--ui-bg) 96%,transparent)!important;border-bottom:1px solid var(--ui-border)!important}.inv15-camera{border:1px solid var(--ui-border)!important;border-radius:16px!important}.inv15-row{background:var(--ui-surface)!important;border:1px solid var(--ui-border)!important;border-radius:11px!important}.inv15-kpi{padding:11px!important}.inv15-kpi span{color:var(--ui-muted)!important}
 .pm-health-section-title{align-items:center!important}.pm-health-grid{gap:12px!important}.pm-hk{min-height:94px!important;padding:14px!important}.pm-health-card{padding:14px!important}
 .modal-bg{backdrop-filter:blur(4px)!important}.modal{background:var(--ui-surface)!important;border:1px solid var(--ui-border)!important;border-radius:16px!important;box-shadow:var(--ui-shadow)!important}.modal-h,.modal-f{background:var(--ui-surface)!important;border-color:var(--ui-border)!important}.kv{background:var(--ui-surface2)!important}.tabs{border-color:var(--ui-border)!important}.tabs button{color:var(--ui-muted)!important}.tabs button.active{color:var(--ui-primary)!important;border-color:var(--ui-primary)!important}
 .ui-mobile-head,.ui-bottom,.ui-more{display:none}
 @media(max-width:1100px){.main{padding:20px!important}.grid4,.pm-health-kpis{grid-template-columns:repeat(2,minmax(0,1fr))!important}.inv15-grid{grid-template-columns:1fr!important}.pm-health-grid{grid-template-columns:1fr!important}}
 @media(max-width:760px){
   html,body{width:100%!important;min-height:100dvh!important;overflow-x:hidden!important}.app{display:block!important;min-height:100dvh!important}.side{display:none!important}.main{margin:0!important;width:100%!important;max-width:none!important;padding:calc(66px + env(safe-area-inset-top)) 12px calc(88px + env(safe-area-inset-bottom))!important}.page{max-width:none!important}.page>.top{display:none!important}
   .ui-mobile-head{position:fixed;z-index:2200;left:0;right:0;top:0;height:calc(58px + env(safe-area-inset-top));padding:env(safe-area-inset-top) 10px 0;display:flex!important;align-items:center;gap:9px;background:color-mix(in srgb,var(--ui-surface) 96%,transparent);border-bottom:1px solid var(--ui-border);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px)}.ui-head-back,.ui-head-action{width:38px;height:38px;border:1px solid var(--ui-border);border-radius:11px;background:var(--ui-surface2);color:var(--ui-text);display:grid;place-items:center;padding:0;flex:0 0 auto}.ui-head-action{background:var(--ui-primary);border-color:var(--ui-primary);color:#fff}.ui-head-back svg,.ui-head-action svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:2;stroke-linecap:round;stroke-linejoin:round}.ui-head-copy{min-width:0;flex:1}.ui-head-copy small{display:block;font-size:8px;color:var(--ui-muted);text-transform:uppercase;letter-spacing:.07em;font-weight:800}.ui-head-copy b{display:block;font-size:16px;letter-spacing:-.3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;margin-top:2px}
   .ui-bottom{position:fixed;z-index:2200;left:0;right:0;bottom:0;height:calc(68px + env(safe-area-inset-bottom));padding:5px 6px env(safe-area-inset-bottom);display:grid!important;grid-template-columns:repeat(5,1fr);align-items:end;background:color-mix(in srgb,var(--ui-surface) 97%,transparent);border-top:1px solid var(--ui-border);box-shadow:0 -8px 28px rgba(0,0,0,.12);backdrop-filter:blur(16px);-webkit-backdrop-filter:blur(16px)}.ui-bottom button{height:55px;min-width:0;border:0;border-radius:12px;background:transparent;color:var(--ui-muted);display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;padding:4px 2px;font:700 8.5px/1 system-ui}.ui-bottom button svg{width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.ui-bottom button.active{color:var(--ui-primary);background:var(--ui-primary-soft)}.ui-bottom .ui-bottom-qr{transform:translateY(-7px);background:transparent!important}.ui-bottom .ui-bottom-qr span:first-child{width:47px;height:47px;border-radius:15px;background:var(--ui-primary);color:#fff;display:grid;place-items:center;box-shadow:0 7px 20px rgba(47,129,247,.3);border:4px solid var(--ui-surface)}.ui-bottom .ui-bottom-qr svg{width:22px;height:22px}
   .ui-more{position:fixed;z-index:3000;inset:0;background:rgba(2,6,12,.58);align-items:flex-end}.ui-more.open{display:flex!important}.ui-more-sheet{width:100%;background:var(--ui-surface);border:1px solid var(--ui-border);border-bottom:0;border-radius:22px 22px 0 0;padding:8px 12px max(16px,calc(10px + env(safe-area-inset-bottom)));box-shadow:0 -20px 55px rgba(0,0,0,.25)}.ui-more-handle{width:38px;height:4px;border-radius:999px;background:var(--ui-border);margin:2px auto 12px}.ui-more-title{display:flex;align-items:center;justify-content:space-between;margin-bottom:8px}.ui-more-title b{font-size:15px}.ui-more-close{width:34px;height:34px;border:1px solid var(--ui-border);border-radius:10px;background:var(--ui-surface2);color:var(--ui-text);display:grid;place-items:center}.ui-more-close svg{width:16px;height:16px;fill:none;stroke:currentColor;stroke-width:2}.ui-more-list{display:grid;gap:7px}.ui-more-item{width:100%;min-height:54px;border:1px solid var(--ui-border);border-radius:13px;background:var(--ui-surface2);color:var(--ui-text);display:grid;grid-template-columns:38px 1fr auto;align-items:center;gap:9px;padding:7px 10px;text-align:left}.ui-more-item .ui-more-icon{width:36px;height:36px;border-radius:10px;background:var(--ui-surface);display:grid;place-items:center;color:var(--ui-primary)}.ui-more-item svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.8}.ui-more-item b{font-size:11px}.ui-more-item small{display:block;font-size:8.5px;color:var(--ui-muted);margin-top:2px}.ui-more-item>span:last-child{color:var(--ui-muted);font-size:18px}
   .grid4,.pm-health-kpis{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:8px!important}.card,.pm-hk{border-radius:14px!important}.stat{min-height:92px!important;padding:12px!important}.stat .num{font-size:21px!important}.stat .lbl{font-size:7.8px!important;line-height:1.25!important}
   .section{margin-top:14px!important}.section-head{margin-bottom:8px!important}.section-head h2{font-size:13px!important}
   .toolbar,.pm-health-toolbar{display:grid!important;grid-template-columns:1fr 1fr!important;gap:7px!important}.toolbar input,.pm-health-toolbar input{grid-column:1/-1!important;width:100%!important;min-width:0!important;min-height:44px!important}.toolbar select,.pm-health-toolbar select{width:100%!important;min-width:0!important;min-height:42px!important}
   #p-dashboard .table{border:0!important;background:transparent!important;overflow:visible!important}#p-dashboard .table table{display:block!important;min-width:0!important}#p-dashboard .table thead{display:none!important}#p-dashboard .table tbody{display:grid!important;gap:7px!important}#p-dashboard .table tr{display:grid!important;grid-template-columns:1fr auto!important;gap:4px 10px!important;background:var(--ui-surface)!important;border:1px solid var(--ui-border)!important;border-radius:13px!important;padding:11px!important}#p-dashboard .table td{display:block!important;border:0!important;padding:0!important;font-size:9.5px!important}#p-dashboard .table td:first-child{grid-column:1/-1!important;font-size:11px!important;font-weight:750!important;margin-bottom:3px!important}#p-dashboard .table td:nth-child(2)::before{content:'Bens · ';color:var(--ui-muted)}#p-dashboard .table td:nth-child(3)::before{content:'Aquisição · ';color:var(--ui-muted)}#p-dashboard .table td:nth-child(4)::before{content:'Atual · ';color:var(--ui-muted)}
   #p-bens .table{border:0!important;background:transparent!important;overflow:visible!important}#p-bens .table table{display:block!important;min-width:0!important}#p-bens .table thead{display:none!important}#p-bens .table tbody{display:grid!important;gap:8px!important}#p-bens .table tr{display:grid!important;grid-template-columns:1fr auto!important;gap:5px 8px!important;background:var(--ui-surface)!important;border:1px solid var(--ui-border)!important;border-radius:14px!important;padding:12px!important}#p-bens .table td{display:block!important;border:0!important;padding:0!important;min-width:0!important}#p-bens .table td:nth-child(1){grid-column:1!important}.code{font-size:13px!important}#p-bens .table td:nth-child(2){grid-column:1/-1!important;font-size:11.5px!important;font-weight:700!important;margin-top:1px!important}#p-bens .table td:nth-child(3){grid-column:1/-1!important;font-size:9.5px!important;color:var(--ui-muted)!important}#p-bens .table td:nth-child(4){display:none!important}#p-bens .table td:nth-child(5){grid-column:1/-1!important;font-size:9.5px!important}#p-bens .table td:nth-child(5)::before{content:'Responsável · ';color:var(--ui-muted)}#p-bens .table td:nth-child(6){grid-column:1!important;margin-top:5px!important;font-size:10px!important}#p-bens .table td:nth-child(7){grid-column:2!important;grid-row:1!important;justify-self:end!important}#p-bens .table td:nth-child(8){grid-column:2!important;justify-self:end!important;align-self:end!important;display:flex!important;gap:5px!important}.link{display:inline-flex!important;align-items:center!important;min-height:32px!important;border:1px solid var(--ui-border)!important;border-radius:9px!important;padding:0 8px!important;background:var(--ui-surface2)!important}
   .scanner-box{max-width:none!important}.scan-frame{min-height:clamp(330px,52dvh,520px)!important;border-radius:18px!important}.scanner-box>.actions{display:grid!important;grid-template-columns:1fr 1fr!important;gap:7px!important}.scanner-box>.actions .btn{width:100%!important;min-height:42px!important}.scan-manual{display:grid!important;grid-template-columns:1fr auto!important}.scan-manual input{width:100%!important;min-width:0!important;min-height:48px!important}.scan-manual .btn{min-width:88px!important}.pm-scan-clear{position:sticky!important;bottom:calc(74px + env(safe-area-inset-bottom))!important;z-index:30!important;box-shadow:0 9px 24px rgba(0,0,0,.18)!important}
   #p-inventario .inv15-head{margin-bottom:12px!important}#p-inventario .inv15-head>div:first-child{display:block!important}#p-inventario .inv15-head h1,#p-inventario .inv15-head p{display:none!important}#p-inventario .inv15-head .btn.primary{display:none!important}.inv15-grid{grid-template-columns:1fr!important;gap:8px!important}.inv15-card{padding:12px!important;border-radius:14px!important}.inv15-stats{gap:5px!important}.inv15-stat{padding:7px!important}.inv15-stat b{font-size:14px!important}.inv15-stat span{font-size:7px!important}.inv15-actions .btn{min-height:38px!important}.inv15-modal{padding:0!important;align-items:flex-end!important}.inv15-sheet{width:100%!important;height:100dvh!important;max-height:100dvh!important;border:0!important;border-radius:0!important}.inv15-sheet-h{padding:calc(10px + env(safe-area-inset-top)) 10px 10px!important}.inv15-sheet-h h2{font-size:15px!important}.inv15-sheet-h .actions{display:flex!important;gap:5px!important;overflow:auto!important}.inv15-sheet-h .btn{flex:0 0 auto!important;padding:6px 8px!important;font-size:8.5px!important}.inv15-sheet-b{padding:10px 10px calc(84px + env(safe-area-inset-bottom))!important}.inv15-kpis{grid-template-columns:repeat(2,1fr)!important;gap:6px!important}.inv15-kpi b{font-size:17px!important}.inv15-work{grid-template-columns:1fr!important;gap:10px!important}.inv15-camera{height:42dvh!important;min-height:290px!important}.inv15-code input{min-width:0!important}.inv15-tabs{overflow:auto!important;flex-wrap:nowrap!important}.inv15-tabs .btn{white-space:nowrap!important;flex:0 0 auto!important}.inv15-list{max-height:none!important}
   .pm-health-section-title{display:none!important}.pm-health-grid{grid-template-columns:1fr!important}.pm-health-table{border:0!important;background:transparent!important;overflow:visible!important}.pm-health-table table{display:block!important;min-width:0!important}.pm-health-table thead{display:none!important}.pm-health-table tbody{display:grid!important;gap:8px!important}.pm-health-table tr{display:block!important;background:var(--ui-surface)!important;border:1px solid var(--ui-border)!important;border-radius:13px!important;padding:11px!important}.pm-health-table td{display:block!important;border:0!important;padding:3px 0!important;font-size:9.5px!important}.pm-health-table td:first-child{font-size:10.5px!important}.pm-health-actions{justify-content:flex-start!important;margin-top:6px!important}
   .settings-grid,.detail-grid,.form-grid,.pm-health-form{grid-template-columns:1fr!important}.fg.two,.fg.full,.pm-health-form .full{grid-column:auto!important}.settings-grid{gap:9px!important}.import-box{padding:22px 12px!important;border-radius:15px!important}
   .modal-bg{padding:0!important;align-items:flex-end!important}.modal{width:100%!important;max-width:none!important;max-height:94dvh!important;border-radius:20px 20px 0 0!important;border-bottom:0!important}.modal-h{padding:11px 12px!important}.modal-b{padding:12px!important}.modal-f{padding:10px 12px calc(10px + env(safe-area-inset-bottom))!important;position:sticky!important;bottom:0!important}.asset-head{grid-template-columns:72px 1fr!important}.asset-photo{width:72px!important;height:62px!important}.asset-code{font-size:18px!important}.asset-title{font-size:14px!important}.detail-grid{gap:6px!important}
 }
 `;document.head.appendChild(s);
}

function navDefinition(page){return PAGE[page]||{label:page,short:page,icon:ICON.more}}
function buildDesktopNav(){
 const brand=document.querySelector('.brand .ico');if(brand)brand.innerHTML=ICON.asset;
 document.querySelectorAll('.nav button[data-page]').forEach(b=>{const d=navDefinition(b.dataset.page);b.innerHTML=`<span class="ui-nav-icon">${d.icon}</span><span class="ui-nav-label">${d.label}</span>`});
 const foot=document.querySelector('.side-foot');if(foot)foot.innerHTML=`<button type="button" id="ui-back-tdn">${ICON.back}<span>Voltar ao TDNGo</span></button>`;
 document.getElementById('ui-back-tdn')?.addEventListener('click',()=>location.href='index.html');
}
function go(page){const b=document.querySelector(`.nav button[data-page="${page}"]`);if(b){b.click();setTimeout(()=>sync(page),0)}}
function actionFor(page){
 if(page==='dashboard'||page==='bens')return typeof window.openAsset==='function'?()=>window.openAsset():null;
 if(page==='inventario')return typeof window.inv15OpenCreate==='function'?()=>window.inv15OpenCreate():null;
 if(page==='manutencao')return typeof window.pmOpenMaintenance==='function'?()=>window.pmOpenMaintenance():null;
 return null;
}
function sync(page){
 page=page||document.querySelector('.nav button.active')?.dataset.page||'dashboard';const d=navDefinition(page),title=document.getElementById('ui-mobile-title'),action=document.getElementById('ui-mobile-action');if(title)title.textContent=d.label;
 document.querySelectorAll('.ui-bottom button[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===page));
 const morePages=['manutencao','relatorios','config','importacao'];document.getElementById('ui-more-btn')?.classList.toggle('active',morePages.includes(page));
 if(action){const fn=actionFor(page);action.style.display=fn?'grid':'none';action.onclick=fn||null}
}
function buildMobile(){
 if(document.getElementById('ui-mobile-head'))return;
 document.body.insertAdjacentHTML('beforeend',`
 <header class="ui-mobile-head" id="ui-mobile-head"><button class="ui-head-back" type="button" aria-label="Voltar ao TDNGo">${ICON.back}</button><div class="ui-head-copy"><small>TDNGo · Patrimônio</small><b id="ui-mobile-title">Visão geral</b></div><button class="ui-head-action" type="button" id="ui-mobile-action" aria-label="Nova ação">${ICON.plus}</button></header>
 <nav class="ui-bottom" aria-label="Navegação do módulo"><button data-page="dashboard" class="active"><span>${ICON.home}</span><span>Início</span></button><button data-page="bens"><span>${ICON.asset}</span><span>Bens</span></button><button data-page="scanner" class="ui-bottom-qr"><span>${ICON.qr}</span><span>QR</span></button><button data-page="inventario"><span>${ICON.inventory}</span><span>Inventário</span></button><button id="ui-more-btn"><span>${ICON.more}</span><span>Mais</span></button></nav>
 <div class="ui-more" id="ui-more"><div class="ui-more-sheet"><div class="ui-more-handle"></div><div class="ui-more-title"><b>Mais opções</b><button class="ui-more-close" type="button">${ICON.close}</button></div><div class="ui-more-list"><button class="ui-more-item" data-page="manutencao"><span class="ui-more-icon">${ICON.wrench}</span><span><b>Manutenção clínica</b><small>Preventiva, corretiva e calibração</small></span><span>›</span></button><button class="ui-more-item" data-page="relatorios"><span class="ui-more-icon">${ICON.chart}</span><span><b>Relatórios</b><small>Indicadores, conformidade e custos</small></span><span>›</span></button><button class="ui-more-item" data-page="config"><span class="ui-more-icon">${ICON.gear}</span><span><b>Configurações</b><small>Locais e parâmetros patrimoniais</small></span><span>›</span></button><button class="ui-more-item" data-page="importacao"><span class="ui-more-icon">${ICON.upload}</span><span><b>Importação inicial</b><small>Carga de patrimônios em lote</small></span><span>›</span></button></div></div></div>`);
 document.querySelector('.ui-head-back').onclick=()=>location.href='index.html';
 document.querySelectorAll('.ui-bottom button[data-page]').forEach(b=>b.onclick=()=>go(b.dataset.page));
 const more=document.getElementById('ui-more');document.getElementById('ui-more-btn').onclick=()=>more.classList.add('open');document.querySelector('.ui-more-close').onclick=()=>more.classList.remove('open');more.addEventListener('click',e=>{if(e.target===more)more.classList.remove('open')});
 document.querySelectorAll('.ui-more-item[data-page]').forEach(b=>b.onclick=()=>{more.classList.remove('open');go(b.dataset.page)});
}
function bindNavigation(){
 document.querySelector('.nav')?.addEventListener('click',e=>{const b=e.target.closest('button[data-page]');if(b)setTimeout(()=>sync(b.dataset.page),0)});
}
function install(){addCss();buildDesktopNav();buildMobile();bindNavigation();sync();document.documentElement.classList.add('pat-ui-v22-ready')}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(install,1800));else setTimeout(install,1800);
})();