(()=>{
'use strict';
const SIX=/^\d{6}$/;let stream=null,video=null,canvas=null,ctx=null,raf=0,state='idle',startPromise=null,stopPromise=null,seq=0,locked='',processing='',miss='',missUntil=0,enginePromise=null,audioCtx=null,lastDecode=0,torch=false;
const $=id=>document.getElementById(id);
function loadEngine(){if(window.jsQR)return Promise.resolve();if(enginePromise)return enginePromise;enginePromise=new Promise((ok,fail)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/jsqr@1.4.0/dist/jsQR.js';s.async=true;s.onload=ok;s.onerror=()=>fail(new Error('Não foi possível carregar o leitor QR.'));document.head.appendChild(s)});return enginePromise}
function status(text,bad=false){const box=document.querySelector('#p-scanner .scanner-box');if(!box)return;let e=box.querySelector('.qr26-state');if(!e){e=document.createElement('div');e.className='qr26-state';box.appendChild(e)}e.classList.toggle('bad',bad);e.textContent=text}
function beep(kind='ok'){try{audioCtx=audioCtx||new(window.AudioContext||window.webkitAudioContext)();const now=audioCtx.currentTime,tones=kind==='ok'?[[920,0,.06],[1280,.07,.07]]:[[320,0,.11],[240,.12,.12]];tones.forEach(([f,d,dur])=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=f;o.type='sine';g.gain.setValueAtTime(.001,now+d);g.gain.exponentialRampToValueAtTime(.12,now+d+.01);g.gain.exponentialRampToValueAtTime(.001,now+d+dur);o.connect(g).connect(audioCtx.destination);o.start(now+d);o.stop(now+d+dur+.02)})}catch{}}
function resultFound(x){const out=$('scan-result');if(!out)return;out.classList.add('show');const money=window.money||((v)=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})),esc=window.esc||String;out.innerHTML=`<div class="asset-head"><div class="asset-photo">🏷️</div><div><div class="asset-code">${esc(x.codigo_patrimonio)}</div><div class="asset-title">${esc(x.descricao)}</div><div class="muted">${esc(x.unidade_nome||'')} · ${esc(x.local_nome||'Sem local definido')}</div></div><button class="btn primary" onclick="openDetail('${x.id}')">Abrir ficha</button></div><div class="detail-grid"><div class="kv"><span>Responsável</span><b>${esc(x.responsavel||'—')}</b></div><div class="kv"><span>Situação</span><b>${esc(x.situacao||'—')}</b></div><div class="kv"><span>Valor atual</span><b>${money(x.depreciacao?.valor_atual)}</b></div></div>`}
function resultMissing(code,msg){const out=$('scan-result');if(!out)return;out.classList.add('show');out.innerHTML=`<div class="empty"><b>QR ${code} não cadastrado.</b><div class="muted" style="margin-top:5px">O leitor continua ativo.</div><div style="margin-top:10px"><button class="btn primary" type="button" onclick="pmRegisterMissing('${code}')">Cadastrar patrimônio</button></div></div>`;document.dispatchEvent(new CustomEvent('pm:scan-missing',{detail:{code,message:msg}}))}
async function onCode(raw){const code=String(raw||'').replace(/\D/g,'').slice(0,6),now=Date.now();if(!SIX.test(code)||locked||processing)return;if(code===miss&&now<missUntil)return;processing=code;if($('scan-code'))$('scan-code').value=code;try{let found=(window.items||[]).find(x=>String(x.codigo_patrimonio)===code);if(!found&&window.post){const r=await window.post({action:'scan',codigo:code});found=r.data}if(!found)throw new Error('Patrimônio não encontrado.');locked=code;miss='';resultFound(found);beep('ok');navigator.vibrate?.([50]);status(`QR ${code} lido · toque em Próximo QR para continuar`);showClear()}catch(e){const msg=String(e?.message||e||'Falha na consulta.'),missing=/não.*(localiz|cadastr|encontr)|nao.*(localiz|cadastr|encontr)|not found|404/i.test(msg);miss=code;missUntil=Date.now()+3500;if(missing){resultMissing(code,msg);status(`QR ${code} não cadastrado · leitor continua ativo`,true)}else{status('Falha na consulta · leitor continua ativo',true)}beep('err')}finally{processing=''}}
function frame(ts){if(state!=='running')return;if(!video||video.readyState<2||!ctx||!window.jsQR){raf=requestAnimationFrame(frame);return}const interval=matchMedia('(max-width:760px)').matches?90:65;if(ts-lastDecode<interval){raf=requestAnimationFrame(frame);return}lastDecode=ts;const vw=video.videoWidth,vh=video.videoHeight;if(vw&&vh){const ratio=matchMedia('(max-width:760px)').matches?.54:.46,roi=Math.max(1,Math.floor(Math.min(vw,vh)*ratio)),sx=Math.floor((vw-roi)/2),sy=Math.floor((vh-roi)/2),target=Math.min(620,roi);if(canvas.width!==target||canvas.height!==target){canvas.width=target;canvas.height=target}ctx.drawImage(video,sx,sy,roi,roi,0,0,target,target);try{const img=ctx.getImageData(0,0,target,target),qr=window.jsQR(img.data,target,target,{inversionAttempts:'attemptBoth'});if(qr)onCode(qr.data)}catch{}}raf=requestAnimationFrame(frame)}
async function tune(track){try{track.contentHint='detail'}catch{}try{const c=track.getCapabilities?.()||{},s=track.getSettings?.()||{},a={};if(c.focusMode?.includes?.('continuous'))a.focusMode='continuous';if(c.exposureMode?.includes?.('continuous'))a.exposureMode='continuous';if(c.whiteBalanceMode?.includes?.('continuous'))a.whiteBalanceMode='continuous';if(c.zoom&&Number.isFinite(c.zoom.min)&&Number.isFinite(c.zoom.max)){const target=matchMedia('(max-width:760px)').matches?1.3:1.15,z=Math.min(c.zoom.max,Math.max(c.zoom.min,target));if(z>Number(s.zoom||c.zoom.min))a.zoom=z}if(Object.keys(a).length)await track.applyConstraints({advanced:[a]})}catch{}}
async function toggleTorch(){const t=stream?.getVideoTracks?.()[0];if(!t)return window.toast?.('Inicie a câmera primeiro.','err');try{const c=t.getCapabilities?.()||{};if(!c.torch)return window.toast?.('A lanterna não é suportada neste aparelho.','err');torch=!torch;await t.applyConstraints({advanced:[{torch}]});const b=$('pm-torch');if(b)b.textContent=torch?'Desligar lanterna':'Lanterna'}catch{window.toast?.('Não foi possível controlar a lanterna.','err')}}
async function stop(){if(stopPromise)return stopPromise;stopPromise=(async()=>{seq++;state='stopping';processing='';torch=false;if(startPromise)try{await startPromise}catch{}if(raf){cancelAnimationFrame(raf);raf=0}const s=stream;stream=null;try{s?.getTracks?.().forEach(t=>t.stop())}catch{}if(video){try{video.pause();video.srcObject=null;video.remove()}catch{}video=null}canvas=null;ctx=null;state='idle';const host=$('qr-reader');if(host)host.innerHTML='<div class="muted">Câmera parada</div>';status('Câmera parada',true)})().finally(()=>stopPromise=null);return stopPromise}
async function start(){if(state==='running'&&stream)return;if(startPromise)return startPromise;startPromise=(async()=>{if(stopPromise)try{await stopPromise}catch{};const host=$('qr-reader');if(!host)return;const my=++seq;state='starting';let ls=null,lv=null;try{await loadEngine();host.innerHTML='';lv=document.createElement('video');lv.setAttribute('playsinline','');lv.autoplay=true;lv.muted=true;lv.style.cssText='width:100%;height:100%;object-fit:cover;display:block';host.appendChild(lv);ls=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:30,max:30}}});if(my!==seq){ls.getTracks().forEach(t=>t.stop());return}stream=ls;video=lv;video.srcObject=ls;await video.play();await tune(ls.getVideoTracks()[0]);canvas=document.createElement('canvas');ctx=canvas.getContext('2d',{willReadFrequently:true});state='running';lastDecode=0;status('Leitor pronto · centralize o QR no quadro');frame(performance.now())}catch(e){try{ls?.getTracks?.().forEach(t=>t.stop())}catch{}stream=null;state='idle';status('Não foi possível iniciar a câmera',true);window.toast?.(String(e?.message||'Não foi possível iniciar a câmera.'),'err')}})().finally(()=>startPromise=null);return startPromise}
function showClear(){const box=document.querySelector('#p-scanner .scanner-box');if(!box)return;let b=box.querySelector('.qr26-clear');if(!b){b=document.createElement('button');b.type='button';b.className='btn qr26-clear';b.textContent='Próximo QR';b.onclick=reset;const out=$('scan-result');out?.insertAdjacentElement('afterend',b)}b.style.display=locked?'inline-flex':'none'}
function reset(){locked='';processing='';miss='';missUntil=0;const out=$('scan-result');if(out){out.classList.remove('show');out.innerHTML=''}if($('scan-code'))$('scan-code').value='';showClear();status('Leitor pronto · centralize o próximo QR');if(state!=='running')start()}
function manual(){const c=String($('scan-code')?.value||'').replace(/\D/g,'').slice(0,6);if(!SIX.test(c))return window.toast?.('Use exatamente 6 dígitos.','err');onCode(c)}
window.pmRegisterMissing=function(code){stop();window.openAsset?.();setTimeout(()=>{const i=$('a-code');if(i){i.value=String(code||'').replace(/\D/g,'').slice(0,6);i.focus()}},30)};
function active(){return $('p-scanner')?.classList.contains('active')}
function install(){const s=document.createElement('style');s.textContent='.qr26-state{text-align:center;margin:8px 0 0;font-size:10px;color:#3f6f52}.qr26-state.bad{color:#a34a4a}.qr26-clear{display:none;margin:10px auto 0}.scan-frame{background:#eef3f7!important;height:320px!important;min-height:0!important;max-height:520px!important}.scan-frame:after{left:50%!important;right:auto!important;top:50%!important;bottom:auto!important;width:190px!important;height:190px!important;transform:translate(-50%,-50%)!important;border-radius:14px!important}@media(max-width:760px){.scan-frame{height:52dvh!important;min-height:320px!important;max-height:520px!important}.scan-frame:after{width:min(58vw,230px)!important;height:min(58vw,230px)!important}}';document.head.appendChild(s);Object.assign(window,{startScanner:start,stopScanner:stop,scanManual:manual,pmScannerReset:reset,pmScannerGetLockedCode:()=>locked,pmToggleTorch:toggleTorch});document.querySelectorAll('[data-page="scanner"]').forEach(b=>b.addEventListener('click',()=>setTimeout(()=>{if(active())start()},60)));document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();else if(active())start()});if(active())setTimeout(start,80)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();