(()=>{
'use strict';
if(window.__TDNGO_PUSH_V1__)return;window.__TDNGO_PUSH_V1__=true;
const PUSH_API='https://nsbhhmrhzkqkaoznaeif.supabase.co/functions/v1/tdngo-manutencao-ext-api';
const SW_URL='./tdngo-push-sw.js?v=20260917-0615';
const GUARD_STORE='tdngo_manut_notif_seen_v27';
let registration=null;
function session(){try{const raw=sessionStorage.getItem('fhsl_session')||localStorage.getItem('fhsl_session');return raw?JSON.parse(raw):null}catch{return null}}
function token(){const s=session();return s?.tdngoToken||s?.token||''}
function isiOS(){return /iPad|iPhone|iPod/i.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)}
function platform(){if(isiOS())return'IOS';if(/android/i.test(navigator.userAgent))return'ANDROID';return'DESKTOP'}
function standalone(){return !!((window.matchMedia&&window.matchMedia('(display-mode: standalone)').matches)||navigator.standalone===true)}
function buttons(){return [...document.querySelectorAll('button')].filter(b=>/enableNotifications\s*\(/.test(b.getAttribute('onclick')||''))}
function setButton(active,unsupported=false){for(const b of buttons()){b.dataset.pushActive=active?'1':'0';b.textContent=unsupported?'Alertas indisponíveis':active?'Alertas 24h ativos':'Ativar alertas';b.title=unsupported?'Este navegador não oferece Web Push.':active?'Notificações Push ativas neste aparelho.':'Ativar notificações Push neste aparelho.'}}
function toast(msg,type=''){const e=document.getElementById('toast');if(!e){console.info('[TDNGo Push]',msg);return}e.textContent=String(msg||'');e.className='toast '+(type||'');e.style.display='block';clearTimeout(e._tdngoPushTimer);e._tdngoPushTimer=setTimeout(()=>e.style.display='none',5200)}
async function api(action,payload={}){const tk=token();if(!tk)throw new Error('Sua sessão expirou. Entre novamente no TDNGo.');const r=await fetch(PUSH_API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+tk},body:JSON.stringify({...payload,action}),cache:'no-store'});const tx=await r.text();let d;try{d=JSON.parse(tx)}catch{d={ok:false,message:tx||`HTTP ${r.status}`}}if(!r.ok||d.ok===false)throw new Error(d.message||`Falha ao configurar alertas (${r.status}).`);return d}
function keyBytes(raw){const pad='='.repeat((4-raw.length%4)%4),bin=atob((raw+pad).replace(/-/g,'+').replace(/_/g,'/'));return Uint8Array.from(bin,c=>c.charCodeAt(0))}
async function getRegistration(){if(!('serviceWorker'in navigator))throw new Error('Este navegador não suporta notificações Push.');if(registration?.active)return registration;registration=await navigator.serviceWorker.register(SW_URL,{scope:'./',updateViaCache:'none'});await navigator.serviceWorker.ready;return registration}
function markSeen(d){const id=String(d?.notification_id||d?.id||'').trim();if(!id)return;try{const o=JSON.parse(localStorage.getItem(GUARD_STORE)||'{}');o['id:'+id]=Date.now();const now=Date.now(),clean={};for(const [k,v] of Object.entries(o))if(Number(v)&&now-Number(v)<7*24*60*60*1000)clean[k]=Number(v);localStorage.setItem(GUARD_STORE,JSON.stringify(clean))}catch{}}
async function status(){if(!window.isSecureContext||!('Notification'in window)||!('PushManager'in window)||!('serviceWorker'in navigator)){setButton(false,true);return{supported:false,active:false}}if(isiOS()&&!standalone()){setButton(false,false);return{supported:true,active:false,needsInstall:true}}try{const reg=await getRegistration(),sub=await reg.pushManager.getSubscription(),active=!!sub&&Notification.permission==='granted';setButton(active,false);return{supported:true,active,permission:Notification.permission,subscription:sub}}catch{setButton(false,false);return{supported:true,active:false}}}
async function enable(){try{if(!window.isSecureContext)throw new Error('As notificações exigem acesso HTTPS.');if(!('Notification'in window)||!('PushManager'in window)||!('serviceWorker'in navigator))throw new Error('Este navegador não suporta notificações Push.');if(isiOS()&&!standalone())throw new Error('No iPhone/iPad: abra no Safari, toque em Compartilhar, escolha “Adicionar à Tela de Início”, abra o TDNGo pelo ícone instalado e toque novamente em “Ativar alertas”.');let p=Notification.permission;if(p==='default')p=await Notification.requestPermission();if(p!=='granted')throw new Error(p==='denied'?'As notificações estão bloqueadas neste aparelho. Libere-as nas configurações do navegador/sistema e tente novamente.':'A permissão de notificações não foi concedida.');const reg=await getRegistration(),k=await api('push_public_key');let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes(String(k.publicKey||''))});await api('push_subscribe',{subscription:sub.toJSON(),plataforma:platform()});setButton(true,false);toast('Alertas Push 24h ativados neste aparelho.','ok');try{navigator.vibrate?.([120,70,120])}catch{}return true}catch(e){setButton(false,false);toast(e.message||'Não foi possível ativar as notificações.','err');return false}}
async function disable(){try{const reg=await getRegistration(),sub=await reg.pushManager.getSubscription();if(sub){const endpoint=sub.endpoint;await sub.unsubscribe();try{await api('push_unsubscribe',{endpoint})}catch{}}setButton(false,false);toast('Alertas Push desativados neste aparelho.','ok');return true}catch(e){toast(e.message||'Não foi possível desativar as notificações.','err');return false}}
function onMessage(ev){const m=ev.data||{};if(m.type!=='TDNGO_MANUT_PUSH_ALERT')return;const d=m.data||{};markSeen(d);const title=String(d.title||'TDNGo Manutenção'),body=String(d.body||d.mensagem||'Novo alerta de manutenção.');toast(body?title+' — '+body:title,'ok');try{navigator.vibrate?.([180,80,180])}catch{}try{if(typeof window.refreshAll==='function')window.refreshAll()}catch{}}
window.enableNotifications=enable;
window.TDNGOPush={enable,disable,status,register:getRegistration};
if('serviceWorker'in navigator)navigator.serviceWorker.addEventListener('message',onMessage);
function init(){if(!token())return;status();window.addEventListener('pageshow',()=>status(),{passive:true});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')status()},{passive:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
