(()=>{
'use strict';
const BASE='https://nsbhhmrhzkqkaoznaeif.supabase.co/functions/v1/';
const API=BASE+'tdngo-manutencao-api',LIVE=BASE+'tdngo-manutencao-live-api',SCOPE=BASE+'tdngo-manutencao-scope-api',INT=BASE+'tdngo-manutencao-internal-api',EXT=BASE+'tdngo-manutencao-ext-api';
const S={session:null,token:'',user:null,permissions:{},tickets:[],notifications:[],oncall:[],units:[],cats:[],photos:[],installPrompt:null,poll:null,lastAlert:new Set()};
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function session(){try{const raw=sessionStorage.getItem('fhsl_session')||localStorage.getItem('fhsl_session');return raw?JSON.parse(raw):null}catch{return null}}
function fmt(v){if(!v)return'—';const d=new Date(v);return isNaN(d)?String(v):d.toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'})}
function since(v){if(!v)return'';const m=Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/60000));if(m<60)return m+' min';const h=Math.floor(m/60);if(h<24)return h+'h '+(m%60)+'min';return Math.floor(h/24)+'d '+(h%24)+'h'}
function toast(m,t=''){const e=$('toast');e.textContent=String(m||'').toLocaleUpperCase('pt-BR');e.className='toast '+t;e.style.display='block';clearTimeout(e._t);e._t=setTimeout(()=>e.style.display='none',4200)}
async function call(url,action,p={}){const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+S.token},body:JSON.stringify({...p,action}),cache:'no-store'});const tx=await r.text();let d;try{d=JSON.parse(tx)}catch{d={ok:false,message:tx}}if(r.status===401){sessionStorage.removeItem('fhsl_session');localStorage.removeItem('fhsl_session');location.replace('../index.html');throw new Error('Sessão expirada')}if(!r.ok||d.ok===false)throw new Error(d.message||'Falha na operação');return d}
function statusLabel(s){return({ABERTO:'Aberto',TRIAGEM:'Triagem',ATRIBUIDO:'Atribuído',EM_ATENDIMENTO:'Em atendimento',AGUARDANDO_MATERIAL:'Aguardando material',AGUARDANDO_TERCEIRO:'Aguardando terceiro',CONCLUIDO:'Concluído',CANCELADO:'Cancelado',REABERTO:'Reaberto'})[s]||s}
function ticketCard(x){const critical=['P1','P2'].includes(x.prioridade);return `<article class="ticket ${critical?'critical':''}" data-id="${x.id}"><div class="ticketTop"><span class="proto">${esc(x.protocolo)}</span><span class="tag ${String(x.prioridade).toLowerCase()}">${esc(x.prioridade)}</span><span class="tag ${x.status==='EM_ATENDIMENTO'?'run':''}">${esc(statusLabel(x.status))}</span>${x.aceite_exigido&&!x.aceito_em?'<span class="tag p1">ACEITE PENDENTE</span>':''}</div><h3>${esc(x.titulo)}</h3><div class="meta">${esc(unitName(x.unidade_id))} · ${esc(x.local_problema||'')}</div><div class="ticketFooter"><span class="time">Aberto há ${since(x.aberto_em)}</span><button class="secondary" data-open="${x.id}">Abrir</button></div></article>`}
function unitName(id){return S.units.find(x=>x.id===id)?.nome||'Unidade'}
function catName(id){return S.cats.find(x=>x.id===id)?.nome||'Categoria'}
function render(){const active=S.tickets.filter(x=>!['CONCLUIDO','CANCELADO'].includes(x.status));$('queueCount').textContent=active.length;$('queue').innerHTML=active.length?active.slice(0,8).map(ticketCard).join(''):'<div class="empty">Nenhum chamado atribuído no momento.</div>';let urgent=[...active].sort((a,b)=>(a.prioridade||'P9').localeCompare(b.prioridade||'P9')||new Date(a.aberto_em)-new Date(b.aberto_em))[0];$('urgent').innerHTML=urgent?`<div class="urgentBox"><div class="callout">${urgent.aceite_exigido&&!urgent.aceito_em?'ACEITE NECESSÁRIO':'PRIORIDADE DO MOMENTO'}</div><h2>${esc(urgent.protocolo)} · ${esc(urgent.prioridade)}</h2><p>${esc(urgent.titulo)}<br>${esc(unitName(urgent.unidade_id))} · ${esc(urgent.local_problema||'')}</p><button class="primary big" data-open="${urgent.id}">${!urgent.aceito_em&&urgent.atribuido_para===S.user?.id?'Aceitar e abrir':'Abrir chamado'}</button></div>`:'<div class="empty">Fila em dia. Nenhum chamado pendente.</div>';$('oncallBanner').innerHTML=S.oncall.length?`<div class="oncall"><b>SOBREAVISO ATIVO</b><span>Você está escalado até ${fmt(S.oncall[0].fim)}.</span></div>`:'';filterMine();renderAlerts();bindOpen()}
function filterMine(){const q=($('search')?.value||'').toUpperCase(),st=$('statusFilter')?.value||'';const rows=S.tickets.filter(x=>(!st||x.status===st)&&(!q||[x.protocolo,x.titulo,x.local_problema,unitName(x.unidade_id)].join(' ').toUpperCase().includes(q)));$('mine').innerHTML=rows.length?rows.map(ticketCard).join(''):'<div class="empty">Nenhum chamado encontrado.</div>';bindOpen()}
function renderAlerts(){const rows=S.notifications||[];$('alertBadge').classList.toggle('hide',!rows.length);$('alertBadge').textContent=rows.length;$('alerts').innerHTML=rows.length?rows.map(n=>`<article class="ticket"><div class="ticketTop"><span class="tag">${esc(n.tipo)}</span><span class="time">${fmt(n.criado_em)}</span></div><h3>${esc(n.titulo)}</h3><div class="meta">${esc(n.mensagem)}</div>${n.chamado_id?`<div class="ticketFooter"><span></span><button class="secondary" data-open="${n.chamado_id}">Abrir chamado</button></div>`:''}</article>`).join(''):'<div class="empty">Nenhum alerta pendente.</div>';bindOpen()}
function bindOpen(){document.querySelectorAll('[data-open]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.onclick=()=>openTicket(b.dataset.open)})}
async function workspace(silent=false){try{const d=await call(LIVE,'workspace');let activeIds=null;try{const scoped=await call(SCOPE,'list');activeIds=new Set((scoped.data||[]).map(x=>String(x.id)));}catch{}S.user=d.user;S.permissions=d.user.permissions||{};S.tickets=(d.tickets||[]).filter(x=>!activeIds||activeIds.has(String(x.id)));S.notifications=(d.notifications||[]).filter(n=>!n.chamado_id||!activeIds||activeIds.has(String(n.chamado_id)));S.oncall=d.my_oncall||[];$('userline').textContent=`${S.user.nome} · ${S.user.perfil}`;if(!['TECNICO','AUXILIAR'].includes(S.user.perfil)&&!new URLSearchParams(location.search).has('preview')){document.body.innerHTML='<div style="padding:28px;font-family:system-ui"><h2>Aplicativo exclusivo da equipe técnica</h2><p>Seu perfil atual é <b>'+esc(S.user.perfil)+'</b>. Use a Central Web para gestão.</p><a href="../manutencao.html">Abrir Central Web</a></div>';return}render();checkNewAlerts()}catch(e){if(!silent)toast(e.message,'err')}}
async function bootstrap(){const d=await call(API,'bootstrap');S.units=d.units||[];S.cats=d.categories||[];fill('nUnit',S.units);fill('nCategory',S.cats);if(S.user)$('nName').value=S.user.nome||''}
function fill(id,rows){const e=$(id);e.innerHTML='<option value="">Selecione...</option>'+rows.map(x=>`<option value="${esc(x.id)}">${esc(x.nome)}</option>`).join('')}
async function openTicket(id){try{const d=await call(API,'detail',{id}),x=d.ticket;$('modalTitle').textContent=x.protocolo;$('modalSub').textContent=`${x.prioridade} · ${statusLabel(x.status)}`;$('modalBody').innerHTML=`<div class="detailGrid"><div class="kv"><span>Unidade</span><b>${esc(unitName(x.unidade_id))}</b></div><div class="kv"><span>Categoria</span><b>${esc(catName(x.categoria_id))}</b></div><div class="kv"><span>Local</span><b>${esc(x.local_problema)}</b></div><div class="kv"><span>Solicitante</span><b>${esc(x.solicitante_nome||'—')}</b></div><div class="kv"><span>Aberto em</span><b>${fmt(x.aberto_em)}</b></div><div class="kv"><span>Prazo</span><b>${fmt(x.prazo_resolucao_em)}</b></div></div><div class="description"><b>${esc(x.titulo)}</b><br><br>${esc(x.descricao)}</div><div class="photoGrid">${(d.photos||[]).map(p=>`<a href="${esc(p.url)}" target="_blank"><img src="${esc(p.url)}"></a>`).join('')}</div>`;const acts=[];if(!x.aceito_em&&(x.atribuido_para===S.user.id||x.escalado_para===S.user.id))acts.push(`<button class="primary" data-act="accept">Aceitar chamado</button>`);if(x.status!=='EM_ATENDIMENTO'&&!['CONCLUIDO','CANCELADO'].includes(x.status))acts.push(`<button class="primary" data-act="start">Iniciar atendimento</button>`);if(!['CONCLUIDO','CANCELADO'].includes(x.status)){acts.push(`<button class="secondary" data-act="note">Andamento</button><button class="secondary" data-act="wait">Aguardar</button><button class="primary" data-act="close">Concluir</button>`)}$('modalActions').innerHTML=acts.join('');$('modal').classList.add('open');document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>ticketAction(b.dataset.act,x))}catch(e){toast(e.message,'err')}}
async function ticketAction(a,x){try{if(a==='accept'){await call(LIVE,'accept',{id:x.id});toast('Chamado aceito.','ok');$('modal').classList.remove('open');await workspace(true);return}if(a==='start'){await call(API,'status',{id:x.id,status:'EM_ATENDIMENTO',nota:''});toast('Atendimento iniciado.','ok');$('modal').classList.remove('open');await workspace(true);return}if(a==='note')return actionForm('Registrar andamento',`<label>Observação<textarea id="aText" required></textarea></label><label>Fotos (opcional)<input id="aFiles" type="file" accept="image/*" capture="environment" multiple></label>`,async()=>{const fotos=await filesToPhotos($('aFiles').files,5);await call(API,'add_note',{id:x.id,nota:$('aText').value,fotos});toast('Andamento registrado.','ok')});if(a==='wait')return actionForm('Aguardar atendimento',`<label>Motivo<select id="aStatus"><option value="AGUARDANDO_MATERIAL">Aguardando material</option><option value="AGUARDANDO_TERCEIRO">Aguardando terceiro</option></select></label><label>Observação<textarea id="aText"></textarea></label>`,async()=>{await call(API,'status',{id:x.id,status:$('aStatus').value,nota:$('aText').value});toast('Status atualizado.','ok')});if(a==='close')return actionForm('Concluir chamado',`<label>Solução executada<textarea id="aText" required></textarea></label><label>Fotos da solução · 1 a 5<input id="aFiles" type="file" accept="image/*" capture="environment" multiple required></label>`,async()=>{const fotos=await filesToPhotos($('aFiles').files,5);if(!fotos.length)throw new Error('Envie ao menos uma foto da solução.');await call(API,'close',{id:x.id,solucao:$('aText').value,fotos});toast('Chamado concluído.','ok')})}catch(e){toast(e.message,'err')}}
function actionForm(title,html,save){$('modalTitle').textContent=title;$('modalSub').textContent='';$('modalBody').innerHTML=`<div class="actionForm">${html}</div>`;$('modalActions').innerHTML='<button class="secondary" id="cancelAction">Cancelar</button><button class="primary" id="saveAction">Salvar</button>';$('cancelAction').onclick=()=>$('modal').classList.remove('open');$('saveAction').onclick=async()=>{const b=$('saveAction');b.disabled=true;try{await save();$('modal').classList.remove('open');await workspace(true)}catch(e){toast(e.message,'err')}finally{b.disabled=false}}}
async function compressFile(file,max=1600,q=.78){if(!file.type.startsWith('image/'))throw new Error('Selecione apenas imagens.');const data=await new Promise((ok,fail)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=fail;r.readAsDataURL(file)});const img=await new Promise((ok,fail)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=fail;i.src=data});let w=img.width,h=img.height,ratio=Math.min(1,max/Math.max(w,h));w=Math.round(w*ratio);h=Math.round(h*ratio);const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);return c.toDataURL('image/jpeg',q)}
async function filesToPhotos(files,max){const out=[];for(const f of [...files].slice(0,max))out.push({data:await compressFile(f),name:f.name});return out}
function maskCpf(v){const d=String(v).replace(/\D/g,'').slice(0,11);return d.replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d)/,'$1.$2').replace(/(\d{3})(\d{1,2})$/,'$1-$2')}
function maskPhone(v){const d=String(v).replace(/\D/g,'').slice(0,11);return d.length<=10?d.replace(/(\d{2})(\d)/,'($1) $2').replace(/(\d{4})(\d)/,'$1-$2'):d.replace(/(\d{2})(\d)/,'($1) $2').replace(/(\d{5})(\d)/,'$1-$2')}
async function submitNew(e){e.preventDefault();const b=$('newSubmit');b.disabled=true;b.textContent='Registrando...';try{const fotos=await filesToPhotos($('nPhotos').files,5);if(!fotos.length)throw new Error('Adicione ao menos uma foto.');const d=await call(INT,'internal_create',{solicitante_nome:$('nName').value,cpf:$('nCpf').value,telefone:$('nPhone').value,unidade_id:$('nUnit').value,setor_solicitante:$('nSector').value,local_problema:$('nLocal').value,categoria_id:$('nCategory').value,impacto:$('nImpact').value,titulo:$('nTitle').value,descricao:$('nDesc').value,fotos,assumir_para_mim:$('nTake').checked});toast(`${d.protocolo} registrado.`,'ok');e.target.reset();$('nName').value=S.user?.nome||'';showPage('now');await workspace(true)}catch(err){toast(err.message,'err')}finally{b.disabled=false;b.textContent='Registrar chamado'}}
async function markRead(){try{await call(LIVE,'mark_alerts');S.notifications=[];renderAlerts();toast('Alertas marcados como lidos.','ok')}catch(e){toast(e.message,'err')}}
function checkNewAlerts(){for(const n of S.notifications){if(S.lastAlert.has(n.id))continue;S.lastAlert.add(n.id);alarm(/P1|P2|CRIT|ESCAL|SOBREAVISO|ACEITE/i.test((n.titulo||'')+' '+(n.mensagem||'')));try{navigator.vibrate?.([300,100,300,100,500])}catch{}}}
let audioCtx=null;async function alarm(critical=false){try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')await audioCtx.resume();const t=audioCtx.currentTime+.03,seq=critical?[[760,1280,.55],[1280,760,.55],[900,1500,.7],[760,1280,.55],[1280,760,.55]]:[[900,1400,.45],[1400,900,.45],[900,1500,.6]];let at=t;for(const [a,b,d] of seq){const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sawtooth';o.frequency.setValueAtTime(a,at);o.frequency.exponentialRampToValueAtTime(b,at+d*.9);g.gain.setValueAtTime(.0001,at);g.gain.exponentialRampToValueAtTime(.8,at+.02);g.gain.exponentialRampToValueAtTime(.0001,at+d);o.connect(g);g.connect(audioCtx.destination);o.start(at);o.stop(at+d+.02);at+=d+.08}}catch{}}
async function enablePush(){try{if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))throw new Error('Push não suportado neste aparelho.');const isiOS=/iphone|ipad|ipod/i.test(navigator.userAgent),standalone=matchMedia('(display-mode:standalone)').matches||navigator.standalone===true;if(isiOS&&!standalone)throw new Error('No iPhone, adicione o aplicativo à Tela de Início primeiro.');const p=await Notification.requestPermission();if(p!=='granted')throw new Error('Permissão de notificação não autorizada.');const reg=await navigator.serviceWorker.ready,key=await call(EXT,'push_public_key');let sub=await reg.pushManager.getSubscription();if(!sub){const raw=key.publicKey,pad='='.repeat((4-raw.length%4)%4),bin=atob((raw+pad).replace(/-/g,'+').replace(/_/g,'/')),arr=Uint8Array.from(bin,c=>c.charCodeAt(0));sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:arr})}await call(EXT,'push_subscribe',{subscription:sub.toJSON(),plataforma:isiOS?'IOS':/android/i.test(navigator.userAgent)?'ANDROID':'DESKTOP'});toast('Alertas 24h ativados.','ok');alarm(false)}catch(e){toast(e.message,'err')}}
function showPage(p){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+p));document.querySelectorAll('.bottom button[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===p));if(p==='mine')filterMine();if(p==='alerts')renderAlerts();window.scrollTo({top:0,behavior:'smooth'})}
function connection(){const on=navigator.onLine;$('connection').textContent=on?'Online':'Sem conexão';$('connection').style.color=on?'':'#c92a2a'}
async function init(){S.session=session();S.token=S.session?.tdngoToken||'';if(!S.token){location.replace('../index.html');return}if('serviceWorker'in navigator)try{await navigator.serviceWorker.register('./sw.js',{scope:'./'});}catch{}await workspace();if(!S.user)return;await bootstrap();$('boot').classList.add('hide');$('app').classList.remove('hide');connection();S.poll=setInterval(()=>workspace(true),15000)}
$('modalClose').onclick=()=>$('modal').classList.remove('open');$('refreshBtn').onclick=()=>workspace();$('alertsBtn').onclick=()=>showPage('alerts');$('markRead').onclick=markRead;$('search').oninput=filterMine;$('statusFilter').onchange=filterMine;$('newForm').onsubmit=submitNew;$('nCpf').oninput=e=>e.target.value=maskCpf(e.target.value);$('nPhone').oninput=e=>e.target.value=maskPhone(e.target.value);$('pushBtn').onclick=enablePush;$('testAlarmBtn').onclick=()=>alarm(true);document.querySelectorAll('.bottom button[data-page]').forEach(b=>b.onclick=()=>showPage(b.dataset.page));window.addEventListener('online',connection);window.addEventListener('offline',connection);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();S.installPrompt=e;$('installBtn').classList.remove('hide')});$('installBtn').onclick=async()=>{if(S.installPrompt){S.installPrompt.prompt();await S.installPrompt.userChoice;S.installPrompt=null;$('installBtn').classList.add('hide')}};document.addEventListener('pointerdown',()=>alarm(false),{once:true});init();
})();