(()=>{'use strict';if(window.__TDNGO_TECH_LIVE_V5__)return;window.__TDNGO_TECH_LIVE_V5__=true;
let syncing=false,last=0,gate=null;const channel=('BroadcastChannel'in window)?new BroadcastChannel('tdngo-manutencao-live'):null;
const $=id=>document.getElementById(id);function role(){const t=String($('userline')?.textContent||'').toUpperCase();return t.includes('AUXILIAR')?'AUXILIAR':t.includes('TECNICO')?'TECNICO':''}
function sync(force=false){if(syncing||document.hidden)return;if(!force&&Date.now()-last<1200)return;const b=$('refreshBtn');if(!b)return;syncing=true;last=Date.now();try{b.click()}catch{}setTimeout(()=>syncing=false,700)}
function announce(){try{channel?.postMessage({type:'refresh',ts:Date.now()})}catch{}setTimeout(()=>sync(true),120)}channel?.addEventListener('message',e=>{if(e.data?.type==='refresh')sync(true)});
const baseFetch=window.fetch.bind(window);window.fetch=async function(input,init){const url=String(typeof input==='string'?input:input?.url||'');let action='';try{if(typeof init?.body==='string')action=JSON.parse(init.body)?.action||''}catch{}const r=await baseFetch(input,init);if(r.ok&&url.includes('/functions/v1/tdngo-manutencao')&&action&&!["workspace","bootstrap","detail","public_status","push_public_key"].includes(action))announce();return r};
async function pushReady(){if(!('serviceWorker'in navigator)||!('PushManager'in window)||!('Notification'in window))return false;if(Notification.permission!=='granted')return false;try{const reg=await navigator.serviceWorker.ready;return !!await reg.pushManager.getSubscription()}catch{return false}}
function makeGate(message='Para utilizar o aplicativo como AUXILIAR, os alertas 24h precisam estar ativos neste dispositivo.') {if(gate)return;gate=document.createElement('div');gate.id='aux-push-gate-v5';gate.style.cssText='position:fixed;inset:0;z-index:99999;background:#f4f7fb;display:grid;place-items:center;padding:22px;font-family:system-ui';gate.innerHTML=`<div style="max-width:420px;background:#fff;border:1px solid #dfe6ee;border-radius:20px;padding:24px;box-shadow:0 18px 50px rgba(0,0,0,.12)"><h2 style="margin:0 0 8px">Alertas obrigatórios</h2><p id="aux-push-msg-v5" style="color:#5f6d7a;line-height:1.5">${message}</p><button id="aux-push-enable-v5" style="width:100%;padding:14px;border:0;border-radius:12px;background:#0f5bd3;color:#fff;font-weight:800">Ativar alertas 24h</button><p style="font-size:12px;color:#7a8794;margin:12px 0 0">Se a permissão estiver bloqueada, libere as notificações nas configurações do navegador ou do aparelho e volte ao aplicativo.</p></div>`;document.body.appendChild(gate);$('aux-push-enable-v5').onclick=()=>{$('pushBtn')?.click();setTimeout(checkGate,900)}}
async function checkGate(){if(role()!=='AUXILIAR'){gate?.remove();gate=null;return}if(await pushReady()){gate?.remove();gate=null;return}let msg='Para utilizar o aplicativo como AUXILIAR, os alertas 24h precisam estar ativos neste dispositivo.';if('Notification'in window&&Notification.permission==='denied')msg='As notificações estão bloqueadas neste aparelho. Libere a permissão do TDNGo nas configurações do navegador/aparelho para continuar.';makeGate(msg);const m=$('aux-push-msg-v5');if(m)m.textContent=msg}
function init(){setInterval(()=>sync(false),2200);setInterval(checkGate,3000);window.addEventListener('focus',()=>{sync(true);checkGate()});document.addEventListener('visibilitychange',()=>{if(!document.hidden){sync(true);checkGate()}});setTimeout(checkGate,900);setTimeout(()=>sync(true),1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();})();