const APP_VERSION='20260917-0900';
const CACHE='tdngo-tech-lite-v6-'+APP_VERSION;
const DEDUP_CACHE='tdngo-tech-push-dedup-v2';
const STATIC_ALLOW=['./manifest.webmanifest','../assets/manutencao-icon.svg'];
const OFFLINE='<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Manutenção</title><body style="font-family:system-ui;padding:24px;background:#f4f7fa;color:#18222d"><h2>Sem conexão</h2><p>Não foi possível abrir o aplicativo da manutenção agora.</p><button onclick="location.reload()" style="padding:10px 14px;border-radius:10px;border:1px solid #cfd8e3;background:#1769d2;color:white;font-weight:700">Tentar novamente</button></body>';
function isStaticAllowed(u){return STATIC_ALLOW.some(x=>u.pathname.endsWith(x.replace('../','/').replace('./','/app-manutencao/')))}
async function networkOnly(req,timeout=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{return await fetch(req,{cache:'no-store',signal:c.signal})}finally{clearTimeout(t)}}
async function nav(req){try{return await networkOnly(req,9000)}catch{return new Response(OFFLINE,{status:503,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store'}})}}
async function staticLight(req){const cache=await caches.open(CACHE);try{const net=await fetch(req,{cache:'reload'});if(net&&net.ok)cache.put(req,net.clone()).catch(()=>{});return net}catch{return (await cache.match(req))||new Response('',{status:504,headers:{'Cache-Control':'no-store'}})}}
self.addEventListener('install',e=>{e.waitUntil((async()=>{const c=await caches.open(CACHE);await Promise.allSettled(STATIC_ALLOW.map(x=>c.add(x)))})());self.skipWaiting()});
self.addEventListener('activate',e=>{e.waitUntil((async()=>{for(const k of await caches.keys())if((k.startsWith('tdngo-tech-')||k.startsWith('tdngo-manut-mobile-'))&&k!==CACHE&&k!==DEDUP_CACHE)await caches.delete(k);await self.clients.claim();const ws=await clients.matchAll({type:'window',includeUncontrolled:true});for(const w of ws){try{w.postMessage({type:'TDNGO_SW_UPDATED',version:APP_VERSION,reload:true});const u=new URL(w.url);if(u.origin===self.location.origin&&u.pathname.includes('/app-manutencao/')){u.searchParams.set('__tdngo_v',APP_VERSION);u.searchParams.set('_sw',Date.now().toString());await w.navigate(u.href)}}catch{}}})())});
self.addEventListener('fetch',e=>{const r=e.request;if(r.method!=='GET')return;const u=new URL(r.url);if(u.origin!==location.origin)return;if(r.mode==='navigate'){e.respondWith(nav(r));return}if(/\.(?:html|js|css)(?:$|\?)/i.test(u.pathname+u.search)){e.respondWith(networkOnly(r,9000).catch(()=>new Response('',{status:504,headers:{'Cache-Control':'no-store'}})));return}if(isStaticAllowed(u)){e.respondWith(staticLight(r));return}});
async function alreadySeenPush(key){if(!key)return false;const c=await caches.open(DEDUP_CACHE),u=new URL('/__tdngo_tech_push__/'+encodeURIComponent(String(key)),self.location.origin),req=new Request(u.toString());if(await c.match(req))return true;await c.put(req,new Response(String(Date.now()),{headers:{'Cache-Control':'max-age=21600'}}));return false}
self.addEventListener('push',e=>{let d={};try{d=e.data?e.data.json():{}}catch{d={body:e.data?.text()||''}};const title=d.title||'TDNGo Manutenção',body=d.body||'Novo alerta de manutenção.';const stableTag=String(d.notification_id||d.id||d.tag||[d.chamado_id||'',d.tipo||'',title,body].join('|')).slice(0,180);const opt={body,icon:'../assets/manutencao-icon.svg',badge:'../assets/manutencao-icon.svg',tag:stableTag,renotify:false,requireInteraction:true,silent:false,data:{url:'./?ticket='+(d.chamado_id||''),chamado_id:d.chamado_id||null,notification_id:d.notification_id||d.id||null}};e.waitUntil((async()=>{if(await alreadySeenPush(stableTag))return;const ws=await clients.matchAll({type:'window',includeUncontrolled:true}),target=ws.find(w=>w.focused||w.visibilityState==='visible');if(target){try{target.postMessage({type:'TDNGO_MANUT_PUSH_ALERT',data:{...d,title,body,tag:stableTag}})}catch{}return}await self.registration.showNotification(title,opt)})())});
self.addEventListener('message',e=>{if(e.data==='SKIP_WAITING')self.skipWaiting();if(e.data==='CLEAR_TDNGO_CACHES')e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('tdngo-tech-')||k.startsWith('tdngo-manut-mobile-')).map(k=>caches.delete(k)))))});
self.addEventListener('notificationclick',e=>{e.notification.close();const target=e.notification?.data?.url||'./';e.waitUntil((async()=>{const ws=await clients.matchAll({type:'window',includeUncontrolled:true});for(const w of ws){if('navigate'in w)try{await w.navigate(target)}catch{}if('focus'in w)return w.focus()}return clients.openWindow(target)})())});
